using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using MusicXmlReaderModel;

namespace MusicBrailleReader
{
    /// <summary>
    /// A first attempt of a Music Braille Editor.
    /// </summary>
    class MusicBrailleEditor
    {
        private Model model;
        private TextBox textBoxRawBraille;
        private ListBox listBoxInterpretedBraille;
        private TextBox editInterpretation;
        private TextBox debugInfo;
        private PerkinsEmulator perkinsEmulator;
        private const char DeleteChar = (char)8;
        private const char SpaceChar = ' ';
        private readonly List<char> charsToPassThrough= new List<char> { DeleteChar, SpaceChar }; // These chars are passed through to the TextBox

        public enum NonPerkinsActionEnum { accept, ignore, ignoreAndBeep }
        NonPerkinsActionEnum nonPerkinsActionEnum = NonPerkinsActionEnum.ignoreAndBeep;


        public void OnTextBoxRawBraille6_KeyDown(object sender, KeyEventArgs e)
        {
            perkinsEmulator.OnDown(e.KeyData);
        }

        public void OnTextBoxRawBraille6_KeyPress(object sender, KeyPressEventArgs e)
        {
            Console.WriteLine(string.Format("textBox1_KeyPress received Unicode {0}", perkinsEmulator.ToDebugString(e.KeyChar)));
            if (perkinsEmulator.IsBraille6(e.KeyChar)) return; // Pass the Braille6 symbol in [0x2800 to 0x283f] on it on to theTextBox
            if (charsToPassThrough.Contains(e.KeyChar)) // Pass other keys explicitly mentioned.
            {
              return ;
            }
            if (perkinsEmulator.IsPerkinschar)
            {
                MarkAsHandled(e);
                return;
            }
            // This was neither a Braille6 [0x2800 .. 0x283F] (generated by the SendKey.Send() nor a PERKINS character S,D,F,J,K,L}. HAndle it as configured.
            switch (nonPerkinsActionEnum)
            {
                case NonPerkinsActionEnum.accept: break;
                case NonPerkinsActionEnum.ignore: MarkAsHandled(e); break;
                case NonPerkinsActionEnum.ignoreAndBeep: MarkAsHandled(e); Beep(); break;
            }
        }

        private void MarkAsHandled(KeyPressEventArgs e)
        {
            Console.WriteLine(string.Format("textBox1_KeyPress sets e.Handled=true"));
            e.Handled = true; // Ignore further handling of this Non-Braille6 key 
        }

        private void Beep()
        {
            Console.WriteLine("BEEP");
            System.Media.SystemSound myBeep = System.Media.SystemSounds.Beep;
            myBeep.Play();
        }



        public void OnTextBoxRawBraille6_KeyUp(object sender, KeyEventArgs e)
        {
            string theBraille6Symbol; // The Unicode representation ("0x2800") of the key endered by the user by simultaneous pressing any combination of F,D,S,J,K,L
            string dotNumbers; // The dotnumbers representation for instance "123456" for all dots present. 
            if ((perkinsEmulator.OnUp(e.KeyCode, out theBraille6Symbol, out dotNumbers)) && (theBraille6Symbol != null))
            {
                Console.WriteLine(string.Format("textBox1_KeyUp calls SendKeys.Send({0}) representing DOT{1}", theBraille6Symbol, dotNumbers));
                SendKeys.Send(theBraille6Symbol);
                OnEdit();
            }
        }

        bool edited = false;

        private void OnEdit()
        {
            edited = true;
        }


        public void OnTextBoxRawBraille6_TextChanged(object sender, EventArgs e)
        {
            if (!edited) return;
            edited = false;
            string editedBrailleText = textBoxRawBraille.Text;
            DecoderItem decoderItem = (DecoderItem)listBoxInterpretedBraille.SelectedItem; // Holds all information about the token we are editing
            string message = BuildMessage(decoderItem, editedBrailleText);
            Logger.LogCF(string.Format(": {0}",message));
            this.debugInfo.Text = message;
            this.editInterpretation.Text = model.DecoderHandler.GetInterpretationString(editedBrailleText, decoderItem);
            // This only handled the UI. The new Braille6 value still needs to be saved !!
        }

        private string BuildMessage(DecoderItem decoderItem, string editedBrailleText)
        { 
            string result = string.Format("StartIndex={0} InitialDecoderState={1} Original token={2} changed to {3}",
                decoderItem.StartIndex, // The startIndex of the item we are editing
                decoderItem.InitialDecoderStateName, // The original state of the statemachine when starting to interpret this token 
                perkinsEmulator.ToDotNumbers(decoderItem.TokenString), // The original tokenString of the token we are editing
                perkinsEmulator.ToDotNumbers(editedBrailleText)); // The edited tokenstring of the token we are editing
            return result;
        }


        public void OnDecodedAsText()
        {
            int decodedLines = listBoxInterpretedBraille.Items.Count;
            if (decodedLines > 0)
            {
                listBoxInterpretedBraille.SelectedIndex = 0;
            }
        }

        public void OnSelectedDecodedLineChanged()
        {
            // TODO: Implement 
            textBoxRawBraille.Clear();
            textBoxRawBraille.Text = "RAW BRAILLE GOES HERE";
            DecoderItem decoderItem = (listBoxInterpretedBraille.SelectedItem as DecoderItem);
            if ((null != decoderItem) & (null != decoderItem.TokenString))
            {
                textBoxRawBraille.Text = decoderItem.TokenString;
            }
        }

        private MusicBrailleEditor(Model model, TextBox textBoxRawBraille, ListBox listBoxInterpretedBraille, TextBox editInterpretation, TextBox debugInfo)
        {
            this.model = model;
            this.textBoxRawBraille = textBoxRawBraille;
            this.listBoxInterpretedBraille = listBoxInterpretedBraille;   
            this.editInterpretation = editInterpretation;
            this.debugInfo = debugInfo;
            this.perkinsEmulator = new PerkinsEmulator();
        }

        public static MusicBrailleEditor Create(Model model, TextBox textBoxRawBraille, ListBox listBoxInterpretedBraille, TextBox editInterpretation, TextBox debugInfo)
        {
            return new MusicBrailleEditor(model, textBoxRawBraille, listBoxInterpretedBraille, editInterpretation,debugInfo);
        }
    }
}
