using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace MusicXmlReaderModel
{

    // https://usermanuals.musicxml.com/MusicXML/Content/CT-MusicXML-direction-type.htm

    public class DirectionTypeElement
    {
        const string className = "DirectionTypeElement";
        DynamicsElement dynamicsElement;
        MetronomeElement metronomeElement;
        WedgeElement wedgeElement;
        WordsElement wordsElement;

        private DirectionTypeElement(XmlNode node)
        {
            const string functionName = "DirectionTypeElement";
            // Dig out elements
            foreach (XmlNode n in node.ChildNodes)
            {
                switch (n.Name)
                {
                    case "dynamics":
                        dynamicsElement = DynamicsElement.Create(n);
                        // This is mentioned in Error 158  so we get rid of the log                 
                        // Logger.LogOnce(string.Format("{0}.{1}: Known but unsupported element. Name={2} ", className, functionName, n.Name));
                        break;
                   
                    case "metronome":
                        metronomeElement = MetronomeElement.Create(n); 
                        break;

                    case "wedge":
                        wedgeElement = WedgeElement.Create(n);
                        break;

                    case "words":
                        wordsElement = WordsElement.Create(n);
                        break;

                    case DoletFinale: // This is an error message from the export from "Finale" using the "Dolet" plugin
                        string s =GetDoletFinaleLogString(n.Value);
                        Logger.LogCFOnce(s); 
                        break;

                    case "symbol": break; // Explicitly ignore graphic information

                    // No current plans for supporting these:
                    case "accordion-registration":
                    case "bracket":
                    case "coda":
                    case "damp":
                    case "damp-all":
                    case "dashes":              
                    case "eyeglasses":
                    case "harp-pedals":
                    case "image":
                    case "octave-shift":
                    case "other-direction":
                    case "pedal":
                    case "percussion":
                    case "principal-voice":
                    case "rehearsal":
                    case "secundatura":
                    case "segno":
                    case "string-mute":
                        // This is mentioned in Error 158  so we get rid of the log 
                        // Logger.LogOnce(string.Format("{0}.{1}: Known but unsupported element. Name={2} ", className, functionName, n.Name));
                        //Logger.LogOnce(string.Format("{0}.{1}: Known but unsupported element.", className, functionName)); // Group them all together
                        break;
                    default: Logger.LogOnce(string.Format("{0}.{1}: Unknown element. Name={2} ",className, functionName, n.Name)); break;
                }
            }

        }

        const string DoletFinale = "DoletFinale";

        // Simple error reporting
        private string GetDoletFinaleLogString(string value)
        {  
            string knownValueStart = "Unrecognized chord suffix";
            string commonFormatString = ": Element generated by the 'Dolet' plugin for 'Finale' as a warning: Name='{0}' Value='{1}' {2}";
            if (value.StartsWith(knownValueStart))
            {
                // If this is recognized as a warning from Finale about "Unrecognized chord suffix" we log it without the details to reduce the amount of loglines.
                return string.Format(commonFormatString, DoletFinale, knownValueStart, "......");
            }
            else
            {
                // If this is recognized as a warning from Finale about anything alse than "Unrecognized chord suffix" we log it with the details including the MusicXml file name
                return string.Format(commonFormatString, DoletFinale, value, "File=" + Model.TheStaticXmlFileName);
            }
        }



        public DynamicsElement DynamicsElement
        {
            get
            {
                return dynamicsElement;
            }
        }

        public MetronomeElement MetronomeElement
        {
            get
            {
                return metronomeElement;
            }
        }



        public WedgeElement WedgeElement
        {
            get
            {
                return wedgeElement;
            }
        }

        public WordsElement WordsElement
        {
            get
            {
                return wordsElement;
            }
        }



        public static DirectionTypeElement Create(XmlNode node)
        {
            return new DirectionTypeElement(node);
        }
    }
}
