using Microsoft.Win32;
using System;
using System.Runtime.InteropServices;
using System.Text;

namespace PlatformDependencies
{
    internal class NativeMethods
    {
#if false
#region FSBrlDspAPI

        // These native methods were used by FSBrlDspAPIWrapper.cs, which has been excluded from the MusicXmlREaderModel.

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)]
        internal static extern int fbOpen(String portName, Int32 h, UInt32 umsgNotify); // Works

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern bool fbBeep(Int32 h);

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern int fbGetCellCount(Int32 h);

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern bool fbGetDisplayName(Int32 h, StringBuilder name, int nMaxChars);

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern bool fbGetFirmwareVersion(Int32 h, StringBuilder name, int nMaxChars);

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern bool fbClose(Int32 h);

        [DllImport("FSBrlDspAPI.dll", CharSet = CharSet.Ansi)] // Works
        internal static extern bool fbWrite(Int32 h, int nStart, int nLength, IntPtr pBytes);
#endregion
#endif

#region SystemParametersInfo
        [DllImport("user32.dll", SetLastError = true)]
        [return: MarshalAs(UnmanagedType.Bool)]
        // internal       static extern bool SystemParametersInfo(uint uiAction, uint uiParam, IntPtr pvParam, uint fWinIni);
        internal static extern bool SystemParametersInfo(uint uiAction, uint uiParam, ref int param, uint fWinIni);
#endregion

#region SHGetKnownFolderPath
        [DllImport("Shell32.dll")]
        internal static extern int SHGetKnownFolderPath(    [MarshalAs(UnmanagedType.LPStruct)]Guid rfid, uint dwFlags, IntPtr hToken,    out IntPtr ppszPath);
        #endregion SHGetKnownFolderPath

        #region FormatMessage

        // https://stackoverflow.com/questions/3823888/how-do-i-look-up-the-proper-windows-system-error-code-to-use-in-my-application
        internal static string GetSystemMessage(int errorCode)
        {
            int capacity = 512;
            int FORMAT_MESSAGE_FROM_SYSTEM = 0x00001000;
            StringBuilder sb = new StringBuilder(capacity);
            FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM, IntPtr.Zero, errorCode, 0,
                sb, sb.Capacity, IntPtr.Zero);
            int i = sb.Length;
            if (i > 0 && sb[i - 1] == 10) i--;
            if (i > 0 && sb[i - 1] == 13) i--;
            sb.Length = i;
            return sb.ToString();
        }

        [DllImport("kernel32.dll")]
        private static extern int FormatMessage(int dwFlags, IntPtr lpSource, int dwMessageId,
        int dwLanguageId, StringBuilder lpBuffer, int nSize, IntPtr Arguments);
        #endregion

        #region RegisterForFileExtension

        // Link:
        // c# - Associate File Extension with Application - Stack Overflow
        //

        internal static void RegisterForFileExtension(string extension, string applicationPath)
        {
                RegistryKey FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + extension);
                FileReg.CreateSubKey("shell\\open\\command").SetValue("", $"\"{applicationPath}\" \"%1\"");
                FileReg.Close();
                SHChangeNotify(0x08000000, 0x0000, IntPtr.Zero, IntPtr.Zero);
        }
        [DllImport("shell32.dll", CharSet = CharSet.Auto, SetLastError = true)]
        public static extern void SHChangeNotify(uint wEventId, uint uFlags, IntPtr dwItem1, IntPtr dwItem2);


#if false
        // AI - generated by Bing:

        public void AddApplicationToRegistry()
        {
            string appPath = @"C:\Path\To\YourApp.exe";
            RegistryKey key = Registry.ClassesRoot.CreateSubKey(@"Applications\YourApp.exe\shell\open\command");
            key.SetValue("", $"\"{appPath}\" \"%1\"");
            key.Close();
        }

        public void AssociateFileExtension()
        {
            string extension = ".yourExtension";
            string progID = "YourAppFile";

            // Create a new ProgID
            RegistryKey progIdKey = Registry.ClassesRoot.CreateSubKey(progID);
            progIdKey.SetValue("", "Your Application File");

            // Set the default icon
            RegistryKey iconKey = progIdKey.CreateSubKey("DefaultIcon");
            iconKey.SetValue("", @"C:\Path\To\YourApp.exe,0");

            // Set the shell open command
            RegistryKey shellKey = progIdKey.CreateSubKey(@"shell\open\command");
            shellKey.SetValue("", $"\"C:\\Path\\To\\YourApp.exe\" \"%1\"");

            // Associate the file extension with the ProgID
            RegistryKey extensionKey = Registry.ClassesRoot.CreateSubKey(extension);
            extensionKey.SetValue("", progID);

            progIdKey.Close();
            iconKey.Close();
            shellKey.Close();
            extensionKey.Close();
        }
#endif


 




#endregion


    }
}
