//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Embosser")]
        public string EmbosserName {
            get {
                return ((string)(this["EmbosserName"]));
            }
            set {
                this["EmbosserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmbosserEscapeSequence {
            get {
                return ((string)(this["EmbosserEscapeSequence"]));
            }
            set {
                this["EmbosserEscapeSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrailleMusicDirectory {
            get {
                return ((string)(this["BrailleMusicDirectory"]));
            }
            set {
                this["BrailleMusicDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRF_ASCII")]
        public string EmbosserFileFormat {
            get {
                return ((string)(this["EmbosserFileFormat"]));
            }
            set {
                this["EmbosserFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int EmbosserPageWidth {
            get {
                return ((int)(this["EmbosserPageWidth"]));
            }
            set {
                this["EmbosserPageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int EmbosserPageHeight {
            get {
                return ((int)(this["EmbosserPageHeight"]));
            }
            set {
                this["EmbosserPageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BrailleMusicDeviceType {
            get {
                return ((string)(this["BrailleMusicDeviceType"]));
            }
            set {
                this["BrailleMusicDeviceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int NoteTakerPageWidth {
            get {
                return ((int)(this["NoteTakerPageWidth"]));
            }
            set {
                this["NoteTakerPageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NoteTakerPageHeight {
            get {
                return ((int)(this["NoteTakerPageHeight"]));
            }
            set {
                this["NoteTakerPageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRF_ASCII")]
        public string NoteTakerFileFormat {
            get {
                return ((string)(this["NoteTakerFileFormat"]));
            }
            set {
                this["NoteTakerFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptionalFormatPageWidth {
            get {
                return ((string)(this["OptionalFormatPageWidth"]));
            }
            set {
                this["OptionalFormatPageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OptionalFormatPageHeight {
            get {
                return ((string)(this["OptionalFormatPageHeight"]));
            }
            set {
                this["OptionalFormatPageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Notetaker")]
        public string NoteTakerName {
            get {
                return ((string)(this["NoteTakerName"]));
            }
            set {
                this["NoteTakerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoteTakerEscapeSequence {
            get {
                return ((string)(this["NoteTakerEscapeSequence"]));
            }
            set {
                this["NoteTakerEscapeSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MusicXmlFile {
            get {
                return ((string)(this["MusicXmlFile"]));
            }
            set {
                this["MusicXmlFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmbosserApplicationName {
            get {
                return ((string)(this["EmbosserApplicationName"]));
            }
            set {
                this["EmbosserApplicationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmbosserApplicationLocation {
            get {
                return ((string)(this["EmbosserApplicationLocation"]));
            }
            set {
                this["EmbosserApplicationLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Universal")]
        public string GenericDeviceName {
            get {
                return ((string)(this["GenericDeviceName"]));
            }
            set {
                this["GenericDeviceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBT0")]
        public string GenericDeviceEscapeSequence {
            get {
                return ((string)(this["GenericDeviceEscapeSequence"]));
            }
            set {
                this["GenericDeviceEscapeSequence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BRF_ASCII")]
        public string GenericDeviceFileFormat {
            get {
                return ((string)(this["GenericDeviceFileFormat"]));
            }
            set {
                this["GenericDeviceFileFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int GenericDevicePageWidth {
            get {
                return ((int)(this["GenericDevicePageWidth"]));
            }
            set {
                this["GenericDevicePageWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int GenericDevicePageHeight {
            get {
                return ((int)(this["GenericDevicePageHeight"]));
            }
            set {
                this["GenericDevicePageHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IBPrint")]
        public string GenericDeviceApplicationName {
            get {
                return ((string)(this["GenericDeviceApplicationName"]));
            }
            set {
                this["GenericDeviceApplicationName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Index Braille\\IbPrint\\IbPrint.exe")]
        public string GenericDeviceApplicationLocation {
            get {
                return ((string)(this["GenericDeviceApplicationLocation"]));
            }
            set {
                this["GenericDeviceApplicationLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\MuseScore 3\\bin\\MuseScore3.exe")]
        public string MuseScoreExe {
            get {
                return ((string)(this["MuseScoreExe"]));
            }
            set {
                this["MuseScoreExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Avid\\Sibelius\\Sibelius.exe")]
        public string SibeliusExe {
            get {
                return ((string)(this["SibeliusExe"]));
            }
            set {
                this["SibeliusExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\capella-software\\capella 8\\bin\\capella.exe")]
        public string CapellaExe {
            get {
                return ((string)(this["CapellaExe"]));
            }
            set {
                this["CapellaExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BANA")]
        public string EmbosserPageLayout {
            get {
                return ((string)(this["EmbosserPageLayout"]));
            }
            set {
                this["EmbosserPageLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BANA")]
        public string NoteTakerPageLayout {
            get {
                return ((string)(this["NoteTakerPageLayout"]));
            }
            set {
                this["NoteTakerPageLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BANA")]
        public string GenericDevicePageLayout {
            get {
                return ((string)(this["GenericDevicePageLayout"]));
            }
            set {
                this["GenericDevicePageLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Finale NotePad 2012\\Finale NotePad.exe")]
        public string FinaleExe {
            get {
                return ((string)(this["FinaleExe"]));
            }
            set {
                this["FinaleExe"] = value;
            }
        }
    }
}
