//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSynthesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForMusicSynthesis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForMusicSynthesis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicSynthesis.ResourcesForMusicSynthesis", typeof(ResourcesForMusicSynthesis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Fifteenth.
        /// </summary>
        internal static string Chord_Function_Augmented_Fifteenth {
            get {
                return ResourceManager.GetString("Chord_Function_Augmented_Fifteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Fifth.
        /// </summary>
        internal static string Chord_Function_Augmented_Fifth {
            get {
                return ResourceManager.GetString("Chord_Function_Augmented_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Fourth.
        /// </summary>
        internal static string Chord_Function_Augmented_Fourth {
            get {
                return ResourceManager.GetString("Chord_Function_Augmented_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Eleventh.
        /// </summary>
        internal static string Chord_Function_AugmentedEleventh {
            get {
                return ResourceManager.GetString("Chord_Function_AugmentedEleventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augmented Ninth.
        /// </summary>
        internal static string Chord_Function_AugmentedNinth {
            get {
                return ResourceManager.GetString("Chord_Function_AugmentedNinth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eleventh.
        /// </summary>
        internal static string Chord_Function_Eleventh {
            get {
                return ResourceManager.GetString("Chord_Function_Eleventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifteenth.
        /// </summary>
        internal static string Chord_Function_Fifteenth {
            get {
                return ResourceManager.GetString("Chord_Function_Fifteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string Chord_Function_Fourth {
            get {
                return ResourceManager.GetString("Chord_Function_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Second.
        /// </summary>
        internal static string Chord_Function_Major_Second {
            get {
                return ResourceManager.GetString("Chord_Function_Major_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Seventh.
        /// </summary>
        internal static string Chord_Function_Major_Seventh {
            get {
                return ResourceManager.GetString("Chord_Function_Major_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Sixth.
        /// </summary>
        internal static string Chord_Function_Major_Sixth {
            get {
                return ResourceManager.GetString("Chord_Function_Major_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Third.
        /// </summary>
        internal static string Chord_Function_Major_Third {
            get {
                return ResourceManager.GetString("Chord_Function_Major_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Fourteenth.
        /// </summary>
        internal static string Chord_Function_MajorFourteenth {
            get {
                return ResourceManager.GetString("Chord_Function_MajorFourteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Thirteenth.
        /// </summary>
        internal static string Chord_Function_MajorThirteenth {
            get {
                return ResourceManager.GetString("Chord_Function_MajorThirteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Ninth.
        /// </summary>
        internal static string Chord_Function_Minor_Ninth {
            get {
                return ResourceManager.GetString("Chord_Function_Minor_Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Second.
        /// </summary>
        internal static string Chord_Function_Minor_Second {
            get {
                return ResourceManager.GetString("Chord_Function_Minor_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Seventh.
        /// </summary>
        internal static string Chord_Function_Minor_Seventh {
            get {
                return ResourceManager.GetString("Chord_Function_Minor_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Sixth.
        /// </summary>
        internal static string Chord_Function_Minor_Sixth {
            get {
                return ResourceManager.GetString("Chord_Function_Minor_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Third.
        /// </summary>
        internal static string Chord_Function_Minor_Third {
            get {
                return ResourceManager.GetString("Chord_Function_Minor_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Fourteenth.
        /// </summary>
        internal static string Chord_Function_MinorFourteenth {
            get {
                return ResourceManager.GetString("Chord_Function_MinorFourteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Thirteenth.
        /// </summary>
        internal static string Chord_Function_MinorThirteenth {
            get {
                return ResourceManager.GetString("Chord_Function_MinorThirteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth.
        /// </summary>
        internal static string Chord_Function_Ninth {
            get {
                return ResourceManager.GetString("Chord_Function_Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string Chord_Function_Octave {
            get {
                return ResourceManager.GetString("Chord_Function_Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string Chord_Function_Perfect_Fifth {
            get {
                return ResourceManager.GetString("Chord_Function_Perfect_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thirteenth.
        /// </summary>
        internal static string Chord_Function_Thirteenth {
            get {
                return ResourceManager.GetString("Chord_Function_Thirteenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonic.
        /// </summary>
        internal static string Chord_Function_Tonic {
            get {
                return ResourceManager.GetString("Chord_Function_Tonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminished Fifth.
        /// </summary>
        internal static string Chord_Function_Tritone {
            get {
                return ResourceManager.GetString("Chord_Function_Tritone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twelfth.
        /// </summary>
        internal static string Chord_Function_Twelfth {
            get {
                return ResourceManager.GetString("Chord_Function_Twelfth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug.
        /// </summary>
        internal static string ChordKind_Aug {
            get {
                return ResourceManager.GetString("ChordKind_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug7.
        /// </summary>
        internal static string ChordKind_Aug7 {
            get {
                return ResourceManager.GetString("ChordKind_Aug7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim.
        /// </summary>
        internal static string ChordKind_Dim {
            get {
                return ResourceManager.GetString("ChordKind_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string ChordKind_Dom11 {
            get {
                return ResourceManager.GetString("ChordKind_Dom11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ChordKind_Dom13 {
            get {
                return ResourceManager.GetString("ChordKind_Dom13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string ChordKind_Dom7 {
            get {
                return ResourceManager.GetString("ChordKind_Dom7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string ChordKind_Dom9 {
            get {
                return ResourceManager.GetString("ChordKind_Dom9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim7.
        /// </summary>
        internal static string ChordKind_FullDim7 {
            get {
                return ResourceManager.GetString("ChordKind_FullDim7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor7b5.
        /// </summary>
        internal static string ChordKind_HalfDim7 {
            get {
                return ResourceManager.GetString("ChordKind_HalfDim7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChordKind_Major {
            get {
                return ResourceManager.GetString("ChordKind_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj11.
        /// </summary>
        internal static string ChordKind_Major11 {
            get {
                return ResourceManager.GetString("ChordKind_Major11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj13.
        /// </summary>
        internal static string ChordKind_Major13 {
            get {
                return ResourceManager.GetString("ChordKind_Major13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ChordKind_Major6 {
            get {
                return ResourceManager.GetString("ChordKind_Major6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj7.
        /// </summary>
        internal static string ChordKind_Major7 {
            get {
                return ResourceManager.GetString("ChordKind_Major7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj9.
        /// </summary>
        internal static string ChordKind_Major9 {
            get {
                return ResourceManager.GetString("ChordKind_Major9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor(maj7).
        /// </summary>
        internal static string ChordKind_MajorMinor {
            get {
                return ResourceManager.GetString("ChordKind_MajorMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor.
        /// </summary>
        internal static string ChordKind_Minor {
            get {
                return ResourceManager.GetString("ChordKind_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor11.
        /// </summary>
        internal static string ChordKind_Minor11 {
            get {
                return ResourceManager.GetString("ChordKind_Minor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor13.
        /// </summary>
        internal static string ChordKind_Minor13 {
            get {
                return ResourceManager.GetString("ChordKind_Minor13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor6.
        /// </summary>
        internal static string ChordKind_Minor6 {
            get {
                return ResourceManager.GetString("ChordKind_Minor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor7.
        /// </summary>
        internal static string ChordKind_Minor7 {
            get {
                return ResourceManager.GetString("ChordKind_Minor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor9.
        /// </summary>
        internal static string ChordKind_Minor9 {
            get {
                return ResourceManager.GetString("ChordKind_Minor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Chord.
        /// </summary>
        internal static string ChordKind_None {
            get {
                return ResourceManager.GetString("ChordKind_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus2.
        /// </summary>
        internal static string ChordKind_Sus2 {
            get {
                return ResourceManager.GetString("ChordKind_Sus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus4.
        /// </summary>
        internal static string ChordKind_Sus4 {
            get {
                return ResourceManager.GetString("ChordKind_Sus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        internal static string DegreeTypeEnum_add {
            get {
                return ResourceManager.GetString("DegreeTypeEnum_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DegreeTypeEnum_alter {
            get {
                return ResourceManager.GetString("DegreeTypeEnum_alter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sub.
        /// </summary>
        internal static string DegreeTypeEnum_subtract {
            get {
                return ResourceManager.GetString("DegreeTypeEnum_subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        internal static string MidiChordDegreeDescription_flat {
            get {
                return ResourceManager.GetString("MidiChordDegreeDescription_flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MidiChordDegreeDescription_natural {
            get {
                return ResourceManager.GetString("MidiChordDegreeDescription_natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharp.
        /// </summary>
        internal static string MidiChordDegreeDescription_sharp {
            get {
                return ResourceManager.GetString("MidiChordDegreeDescription_sharp", resourceCulture);
            }
        }
    }
}
