//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicSynthesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForMusicSynthesis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForMusicSynthesis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicSynthesis.ResourcesForMusicSynthesis", typeof(ResourcesForMusicSynthesis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug.
        /// </summary>
        internal static string ChordKind_Aug {
            get {
                return ResourceManager.GetString("ChordKind_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug7.
        /// </summary>
        internal static string ChordKind_Aug7 {
            get {
                return ResourceManager.GetString("ChordKind_Aug7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim.
        /// </summary>
        internal static string ChordKind_Dim {
            get {
                return ResourceManager.GetString("ChordKind_Dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string ChordKind_Dom11 {
            get {
                return ResourceManager.GetString("ChordKind_Dom11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13.
        /// </summary>
        internal static string ChordKind_Dom13 {
            get {
                return ResourceManager.GetString("ChordKind_Dom13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string ChordKind_Dom7 {
            get {
                return ResourceManager.GetString("ChordKind_Dom7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string ChordKind_Dom9 {
            get {
                return ResourceManager.GetString("ChordKind_Dom9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim7.
        /// </summary>
        internal static string ChordKind_FullDim7 {
            get {
                return ResourceManager.GetString("ChordKind_FullDim7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half-diminished.
        /// </summary>
        internal static string ChordKind_HalfDim7 {
            get {
                return ResourceManager.GetString("ChordKind_HalfDim7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChordKind_Major {
            get {
                return ResourceManager.GetString("ChordKind_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj11.
        /// </summary>
        internal static string ChordKind_Major11 {
            get {
                return ResourceManager.GetString("ChordKind_Major11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj13.
        /// </summary>
        internal static string ChordKind_Major13 {
            get {
                return ResourceManager.GetString("ChordKind_Major13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string ChordKind_Major6 {
            get {
                return ResourceManager.GetString("ChordKind_Major6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj7.
        /// </summary>
        internal static string ChordKind_Major7 {
            get {
                return ResourceManager.GetString("ChordKind_Major7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj9.
        /// </summary>
        internal static string ChordKind_Major9 {
            get {
                return ResourceManager.GetString("ChordKind_Major9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min(maj7).
        /// </summary>
        internal static string ChordKind_MajorMinor {
            get {
                return ResourceManager.GetString("ChordKind_MajorMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string ChordKind_Minor {
            get {
                return ResourceManager.GetString("ChordKind_Minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m11.
        /// </summary>
        internal static string ChordKind_Minor11 {
            get {
                return ResourceManager.GetString("ChordKind_Minor11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m13.
        /// </summary>
        internal static string ChordKind_Minor13 {
            get {
                return ResourceManager.GetString("ChordKind_Minor13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m6.
        /// </summary>
        internal static string ChordKind_Minor6 {
            get {
                return ResourceManager.GetString("ChordKind_Minor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m7.
        /// </summary>
        internal static string ChordKind_Minor7 {
            get {
                return ResourceManager.GetString("ChordKind_Minor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m9.
        /// </summary>
        internal static string ChordKind_Minor9 {
            get {
                return ResourceManager.GetString("ChordKind_Minor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus2.
        /// </summary>
        internal static string ChordKind_Sus2 {
            get {
                return ResourceManager.GetString("ChordKind_Sus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus4.
        /// </summary>
        internal static string ChordKind_Sus4 {
            get {
                return ResourceManager.GetString("ChordKind_Sus4", resourceCulture);
            }
        }
    }
}
