using System.Windows.Forms;

/// <summary>
/// For implementing application-independent, general UI tools for improved accessiblity 
/// </summary>
namespace UiAccessibilityModel
{
    public class MenuItemHandler
    {
        // The following default values can be overridden by Create(,,)
        private string control = "CONTROL"; // "Localized" to English. 
        private string alt = "ALT";// "Localized" to English. 
        private string shift = "SHIFT";// "Localized" to English.

        /// <summary>
        /// Fills in the ToolStripMenuItem with text and shortcutkeys including an autogenerated AccessibleName well suited for JAWS
        /// </summary>
        /// <param name="menuItem">The ToolStripMenuItem to modify</param>
        /// <param name="text">The visible Menu item name (possibly including an amphersand for defining an access key)</param>
        /// <param name="shortCutKeys">The shortcut key combination (if any)</param>
        public void GenerateAccessibleName(ToolStripMenuItem menuItem, string text, Keys shortCutKeys)
        {
            string keyString = KeysToString(shortCutKeys);
            menuItem.Text = text;
            menuItem.ShortcutKeys = shortCutKeys;
            menuItem.AccessibleName = RemoveAmpersant(text) + " " + keyString; // JAWS speaks the ShortcutKey before the AccessKey: "Files" "Control plus f" "f"
        }

        /// <summary>
        /// Borrowed from C:\Users\Jens\Dropbox\Visual Studio 2015\Solutions\Tactile MusicXmlReader\MusicXmlReader\UiUtilities.cs
        /// Converts a Windows.Forms.Keys to a string.
        /// Faces the problem that the standard Keys.ToString() converts digits to "D0" to "D9" not "0" to "9"
        /// </summary>
        /// <param name="keys"></param>
        /// <returns></returns>
        public string KeysToString(Keys keys)
        {
            if (Keys.None == keys) return "";
            string controlString = (0 != (keys & Keys.Control)) ? control + "+" : "";
            string altString = (0 != (keys & Keys.Alt)) ? alt + "+" : "";
            string shiftString = (0 != (keys & Keys.Shift)) ? shift + "+" : "";
            Keys simpleKey = keys & ~(Keys.Control | Keys.Alt | Keys.Shift);
            string charString = simpleKey.ToString(); // Will generate "D0" to "D9" for the digits !
            if ((simpleKey >= Keys.D0) && (simpleKey <= Keys.D9))
            {
                char c = (char)('0' + (char)(simpleKey - Keys.D0));
                charString = c.ToString();
            }
            return controlString + altString + shiftString + charString;
        }

        /// <summary>
        /// Remove any occurance of the "&" character from the string.
        /// Used in the UI for using the same localized text resource both for assigning an ALT shortcut (marked by the "&") and as a normal string (aftert removing the "&")
        /// </summary>
        /// <param name="s"></param>
        /// <returns></returns>
        private string RemoveAmpersant(string s)
        {
            if (null == s) return s;
            return s.Replace("&", "");
        }
        
        private MenuItemHandler()
        { }

        private MenuItemHandler(string control, string alt, string shift)
        {
            this.control = control;
            this.alt = alt;
            this.shift = shift;
        }

        /// <summary>
        /// Use this Create in order to overwrite the default English terms with actual, localized values.
        /// </summary>
        /// <param name="control"></param>
        /// <param name="alt"></param>
        /// <param name="shift"></param>
        /// <returns></returns>
        public static MenuItemHandler Create(string control, string alt, string shift)
        {
            return new MenuItemHandler(control, alt,shift);
        }

        /// <summary>
        /// USe this Create to maintain default English localization.
        /// </summary>
        /// <returns></returns>
        public static MenuItemHandler Create()
        {
            return new MenuItemHandler();
        }
    }
}
