using System;
using System.Collections.Generic;
//using MusicXmlReaderUI;

namespace MusicXmlReaderModel
{

    public class EventDescriptionList
    {

        UserSettings userSettings;

        /// <summary>
        /// To force the use of the Create() method
        /// </summary>
        private EventDescriptionList()
        {
        }

        List<EventDescription> events;

        public List<EventDescription> Events
        {
            get
            {
                return events;
            }
        }

        /// <summary>
        /// Private constructor, used by the Crate() method
        /// </summary>
        /// <param name="node"></param>
        private EventDescriptionList(TimeDescriptionList timeDescriptionList, int numberOfParts,UserSettings userSettings,StatusInformation currentStatusInformation)
        {
            this.userSettings = userSettings;
            events = new List<EventDescription>();
            Int64 currentStartTime = -1;
            EventDescription currentEventDescription = null;
            foreach (EventElement eventElement in timeDescriptionList.times)
            {
                if (eventElement.StartTime != currentStartTime)
                {
                    // Time has changed, so we need a new event Description
                 
                    // Enable the next line to investigate problems with synchronizing voices (primarily in .xml files generated by Sibelius, not by MuseScore)
                    // if (0 != eventElement.StartTime) Logger.LogOnce(string.Format("{0}.{0} eventElement.StartTime-currentStartTime= {1}", "EventDescriptionList", (eventElement.StartTime - currentStartTime))); // Debug only !

                    if (null != currentEventDescription)
                    {
                        // Save a copy of the currrent status information with the eventDescription, we have just finished:
                        currentEventDescription.StatusInformation = StatusInformation.Create(currentStatusInformation);                     
                    }

                    currentStartTime = eventElement.StartTime;
                    currentEventDescription = EventDescription.Create(currentStartTime, numberOfParts, this.userSettings);      
                    events.Add(currentEventDescription);
                }
                currentEventDescription.AddNode(eventElement, currentStatusInformation);
            }

        }

        public static EventDescriptionList Create(TimeDescriptionList timeDescriptionList, int numberOfParts, UserSettings userSettings, StatusInformation currentStatusInformation)
        {
            return new EventDescriptionList(timeDescriptionList, numberOfParts,userSettings,currentStatusInformation);
        }


    }
}
