using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Win32;
using NAudio.Gui;
using PlatformDependencies;
using static MusicXmlReaderModel.BrailleBuilderForMusic;

namespace MusicXmlReaderModel
{
    internal class FileAssociations
    {
 
        private static void LogRegistryInformation(RegistryKey key)
        {
            object o = key.GetValue("");
            if (null == o)
            {
                Logger.LogCF1(string.Format(": KeyName={0} DOES NOT EXTST!", key.Name));
            }
            else
            {
                Logger.LogCF1(string.Format(": KeyName={0} KeyValue={1}", key.Name, o.ToString()));
            }               

        }


        public static void LogAssociationInformation(string extension, string progId)
        {
            RegistryKey key = null;
            RegistryKey progIdKey = null;
            RegistryKey commandKey = null;    
            RegistryKey userChoiseKey = null;
            try // Be sure to leave all registry keys closed !
            {
                key = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{extension}");
                LogRegistryInformation(key);

                progIdKey = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{progId}");
                LogRegistryInformation(progIdKey);

                commandKey = progIdKey.CreateSubKey(@"shell\open\command");
                LogRegistryInformation(commandKey);
  
                userChoiseKey = Registry.CurrentUser.OpenSubKey(ExplorerFileExtsKeyName + extension + "\\" + UserChoiseSubKeyName, true);
                LogRegistryInformation(userChoiseKey);       
            }
            catch (Exception e)
            {
                Logger.LogCFE(e);
            }

            if (null != key) key.Close();
            if (null != progIdKey) progIdKey.Close();
            if (null != commandKey) commandKey.Close();
            if (null != userChoiseKey) userChoiseKey.Close();
        }


        /// <summary>
        /// Associate the extension with the application
        /// </summary>
        /// <param name="extension"></param>
        /// <param name="applicationPath"></param>
        /// <returns></returns>
        public static void RegisterForFileExtension(string extension, string progId, string applicationPath)
        {
            RegistryKey key = null;
            RegistryKey progIdKey = null;
            RegistryKey commandKey = null;
            try // Be sure to close all keys
            {
                // AI - generated by Bing:
                // Create a new key for the file extension
                key = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{extension}");
                key.SetValue("", progId);

                // Create a new key for the ProgID
                progIdKey = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{progId}");
                progIdKey.SetValue("", ""); // Could be used for supplementary information

                // Create a new key for the application
                commandKey = progIdKey.CreateSubKey(@"shell\open\command");
                commandKey.SetValue("", $"\"{applicationPath}\" \"%1\"");
            }
            catch (Exception e)
            {
                Logger.LogCFE(e);
            }
            if (null != key) key.Close() ;
            if (null != progIdKey) progIdKey.Close();
            if (null != commandKey) commandKey.Close();

            ChangeExplorerAssociation(extension,progId); // See comment below

            NativeMethods.ShellChangeNotify();          
        }



        //// Older method
        ////  // c# - Associate File Extension with Application - Stack Overflow
        //RegistryKey FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + extension);
        //FileReg.CreateSubKey("shell\\open\\command").SetValue("", $"\"{applicationPath}\" \"%1\"");
        //FileReg.Close();


        /// <summary>
        /// The plase where Windows Explorer casches information about User expensin preferences!
        /// </summary>
        private const string ExplorerFileExtsKeyName = "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\";
        private const string UserChoiseSubKeyName = "UserChoice";

        /// <summary>
        /// Another method inspired by 
        ///  https://stackoverflow.com/questions/2681878/associate-file-extension-with-application/2697804#2697804
        /// where the author says:
        /// "The answer was a lot simpler than I expected.
        ///  Windows Explorer has its own override for the open with application, and I was trying to modify it in the last lines of code.
        ///  If you just delete the Explorer override, then the file association will work.
        ///  I also told explorer that I had changed a file association by calling the unmanaged function"
        /// </summary>
        /// <param name="Extension"></param>
        public static void ChangeExplorerAssociation(string Extension,string progId)
        {       
            RegistryKey key = null;
            try
            {
                // The key will typically be: "Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.musicXml"
                // Delete the key instead of trying to change it
                key = Registry.CurrentUser.OpenSubKey(ExplorerFileExtsKeyName + Extension, true);
                if (null != key)
                {
                    key.DeleteSubKey(UserChoiseSubKeyName, false);
                    // Create a new subkey 
                    key.CreateSubKey(UserChoiseSubKeyName).SetValue("", progId); // "UserChoice";
                }
            }
            catch (Exception e)
            {
                Logger.LogCFE(e);
            }
            if (null != key) key.Close();
        }



    }
}
