using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Win32;
using PlatformDependencies;

namespace MusicXmlReaderModel
{
    internal class FileAssociations
    {
        /// <summary>
        /// Primarily for debugging: 
        /// Lists the assocations for a given file extension, as found in CurrentUser, LocalMAchine and ClassesRoot
        /// </summary>
        /// <param name="extension">The extension to look for</param>
        /// <returns></returns>
        public static List<string> GetAssociationInformation(string extension)
        {
            List<string> result = new List<string>();
            RegistryKey FileReg = null;

            string HKCU_value = "";
            try
            {
                FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + extension);
                HKCU_value = FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKCU_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }

            string HKLM_value = "";
            try
            {
                FileReg = Registry.LocalMachine.CreateSubKey("Software\\Classes\\" + extension);
                HKLM_value = FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKLM_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }


            string HKCR_value = "";
            try
            {
                FileReg = Registry.ClassesRoot.CreateSubKey("" + extension);
                HKCR_value = FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKCR_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }


            result.Add("HKCU: " + HKCU_value);
            result.Add("HKLM: " + HKLM_value);
            result.Add("HKCR: " + HKCR_value);            
            return result;
        }


        /// <summary>
        /// Associate the extension with the application
        /// </summary>
        /// <param name="extension"></param>
        /// <param name="applicationPath"></param>
        /// <returns></returns>
        public static void RegisterForFileExtension(string extension, string progId, string applicationPath)
        {
#if true
            // AI - generated by Bing:
            // Create a new key for the file extension
            RegistryKey key = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{extension}");
            key.SetValue("", progId);

            // Create a new key for the ProgID
            RegistryKey progIdKey = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{progId}");
            progIdKey.SetValue("", "My Application");

            // Create a new key for the application
            RegistryKey commandKey = progIdKey.CreateSubKey(@"shell\open\command");
            commandKey.SetValue("", $"\"{applicationPath}\" \"%1\"");
#else
            // Older method
            //  // c# - Associate File Extension with Application - Stack Overflow
            RegistryKey FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + extension);
            FileReg.CreateSubKey("shell\\open\\command").SetValue("", $"\"{applicationPath}\" \"%1\"");
            FileReg.Close();
#endif
            NativeMethods.ShellChangeNotify();
        }

    }
}
