using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using Microsoft.Win32;
using NAudio.Gui;
using PlatformDependencies;
using static MusicXmlReaderModel.BrailleBuilderForMusic;

namespace MusicXmlReaderModel
{
    internal class FileAssociations
    {
        /// <summary>
        /// Primarily for debugging: 
        /// Lists the assocations for a given file extension, as found in CurrentUser, LocalMAchine and ClassesRoot
        /// </summary>
        /// <param name="extension">The extension to look for</param>
        /// <returns></returns>
        public static List<string> GetAssociationInformation(string progId)
        {
            List<string> result = new List<string>();
            RegistryKey FileReg = null;

 
            string HKCU_value = "";
            try
            {
                FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + progId);
                HKCU_value = FileReg.Name + " = " + FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKCU_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }

            string HKLM_value = "";
            try
            {
                FileReg = Registry.LocalMachine.CreateSubKey("Software\\Classes\\" + progId);
                HKLM_value = FileReg.Name + " = " + FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKLM_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }


            string HKCR_value = "";
            try
            {
                FileReg = Registry.ClassesRoot.CreateSubKey("" + progId);
                HKCR_value = FileReg.Name + " = " + FileReg.OpenSubKey("shell\\open\\command").GetValue("").ToString();
            }
            catch (Exception e)
            {
                HKCR_value = "Can not be read! Message=" + e.Message;
            }
            if (null != FileReg) { FileReg.Close(); }


            result.Add("HKCU: " + HKCU_value);
            result.Add("HKLM: " + HKLM_value);
            result.Add("HKCR: " + HKCR_value);            
            return result;
        }


        /// <summary>
        /// Associate the extension with the application
        /// </summary>
        /// <param name="extension"></param>
        /// <param name="applicationPath"></param>
        /// <returns></returns>
        public static void RegisterForFileExtension(string extension, string progId, string applicationPath)
        {
#if true
            // AI - generated by Bing:
            // Create a new key for the file extension
            RegistryKey key = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{extension}");
            key.SetValue("", progId);

            // Create a new key for the ProgID
            RegistryKey progIdKey = Registry.CurrentUser.CreateSubKey($"Software\\Classes\\{progId}");
            progIdKey.SetValue("", "My Application");

            // Create a new key for the application
            RegistryKey commandKey = progIdKey.CreateSubKey(@"shell\open\command");
            commandKey.SetValue("", $"\"{applicationPath}\" \"%1\"");
#else
            // Older method
            //  // c# - Associate File Extension with Application - Stack Overflow
            RegistryKey FileReg = Registry.CurrentUser.CreateSubKey("Software\\Classes\\" + extension);
            FileReg.CreateSubKey("shell\\open\\command").SetValue("", $"\"{applicationPath}\" \"%1\"");
            FileReg.Close();
#endif
            ChangeExplorerAssociation(extension,progId); // See comment below
            NativeMethods.ShellChangeNotify();
        }


        /// <summary>
        /// Another method inspired by 
        ///  https://stackoverflow.com/questions/2681878/associate-file-extension-with-application/2697804#2697804
        /// where the author says:
        /// "The answer was a lot simpler than I expected.
        ///  Windows Explorer has its own override for the open with application, and I was trying to modify it in the last lines of code.
        ///  If you just delete the Explorer override, then the file association will work.
        ///  I also told explorer that I had changed a file association by calling the unmanaged function"
        /// </summary>
        /// <param name="Extension"></param>
        public static void ChangeExplorerAssociation(string Extension,string progId)
        {
            // The stuff that was above here is basically the same


            // Delete the key instead of trying to change it
            var CurrentUser = Registry.CurrentUser.OpenSubKey("Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\" + Extension, true);
            CurrentUser.DeleteSubKey("UserChoice", false);
            // Create a new subkey 
            CurrentUser.CreateSubKey("UserChoise").SetValue("",progId);
            CurrentUser.Close();

            // Tell explorer the file association has been changed
            NativeMethods.ShellChangeNotify();
        }



    }
}
