//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReaderModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReaderModel.ResourcesForModel", typeof(ResourcesForModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        internal static string AccidentalMarkElement_flat {
            get {
                return ResourceManager.GetString("AccidentalMarkElement_flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural.
        /// </summary>
        internal static string AccidentalMarkElement_natural {
            get {
                return ResourceManager.GetString("AccidentalMarkElement_natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharp.
        /// </summary>
        internal static string AccidentalMarkElement_sharp {
            get {
                return ResourceManager.GetString("AccidentalMarkElement_sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidentalmark.
        /// </summary>
        internal static string AccidentalMarkElement_text {
            get {
                return ResourceManager.GetString("AccidentalMarkElement_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggiate downwards.
        /// </summary>
        internal static string ArpeggiateElement_downwards {
            get {
                return ResourceManager.GetString("ArpeggiateElement_downwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggiate upwards.
        /// </summary>
        internal static string ArpeggiateElement_upwards {
            get {
                return ResourceManager.GetString("ArpeggiateElement_upwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accent.
        /// </summary>
        internal static string ArticulationsElement_Accent {
            get {
                return ResourceManager.GetString("ArticulationsElement_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breathmark.
        /// </summary>
        internal static string ArticulationsElement_BreathMark {
            get {
                return ResourceManager.GetString("ArticulationsElement_BreathMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caesura.
        /// </summary>
        internal static string ArticulationsElement_Caesura {
            get {
                return ResourceManager.GetString("ArticulationsElement_Caesura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to detached legato.
        /// </summary>
        internal static string ArticulationsElement_DetatchedLegato {
            get {
                return ResourceManager.GetString("ArticulationsElement_DetatchedLegato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doit.
        /// </summary>
        internal static string ArticulationsElement_Doit {
            get {
                return ResourceManager.GetString("ArticulationsElement_Doit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to falloff.
        /// </summary>
        internal static string ArticulationsElement_Falloff {
            get {
                return ResourceManager.GetString("ArticulationsElement_Falloff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other articulation.
        /// </summary>
        internal static string ArticulationsElement_OtherArticulation {
            get {
                return ResourceManager.GetString("ArticulationsElement_OtherArticulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plop.
        /// </summary>
        internal static string ArticulationsElement_Plop {
            get {
                return ResourceManager.GetString("ArticulationsElement_Plop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scoop.
        /// </summary>
        internal static string ArticulationsElement_Scoop {
            get {
                return ResourceManager.GetString("ArticulationsElement_Scoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spiccato.
        /// </summary>
        internal static string ArticulationsElement_Spiccato {
            get {
                return ResourceManager.GetString("ArticulationsElement_Spiccato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staccatissimo.
        /// </summary>
        internal static string ArticulationsElement_Staccatissimo {
            get {
                return ResourceManager.GetString("ArticulationsElement_Staccatissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to staccato.
        /// </summary>
        internal static string ArticulationsElement_Staccato {
            get {
                return ResourceManager.GetString("ArticulationsElement_Staccato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stress.
        /// </summary>
        internal static string ArticulationsElement_Stress {
            get {
                return ResourceManager.GetString("ArticulationsElement_Stress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strong accent.
        /// </summary>
        internal static string ArticulationsElement_StrongAccent {
            get {
                return ResourceManager.GetString("ArticulationsElement_StrongAccent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tenuto.
        /// </summary>
        internal static string ArticulationsElement_Tenuto {
            get {
                return ResourceManager.GetString("ArticulationsElement_Tenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unstress.
        /// </summary>
        internal static string ArticulationsElement_Unstress {
            get {
                return ResourceManager.GetString("ArticulationsElement_Unstress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barline.
        /// </summary>
        internal static string BarlineElement {
            get {
                return ResourceManager.GetString("BarlineElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        internal static string BarlineElement_Position_left {
            get {
                return ResourceManager.GetString("BarlineElement_Position_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middle.
        /// </summary>
        internal static string BarlineElement_Position_middle {
            get {
                return ResourceManager.GetString("BarlineElement_Position_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        internal static string BarlineElement_Position_right {
            get {
                return ResourceManager.GetString("BarlineElement_Position_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string BarlineElement_Position_unknown {
            get {
                return ResourceManager.GetString("BarlineElement_Position_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-Clef.
        /// </summary>
        internal static string ClefElement_C_Key {
            get {
                return ResourceManager.GetString("ClefElement_C_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-Clef.
        /// </summary>
        internal static string ClefElement_F_Key {
            get {
                return ResourceManager.GetString("ClefElement_F_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Clef.
        /// </summary>
        internal static string ClefElement_G_Key {
            get {
                return ResourceManager.GetString("ClefElement_G_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jianpu.
        /// </summary>
        internal static string ClefElement_jianpu {
            get {
                return ResourceManager.GetString("ClefElement_jianpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Clef.
        /// </summary>
        internal static string ClefElement_None {
            get {
                return ResourceManager.GetString("ClefElement_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percussion.
        /// </summary>
        internal static string ClefElement_Percussion {
            get {
                return ResourceManager.GetString("ClefElement_Percussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB.
        /// </summary>
        internal static string ClefElement_TAB {
            get {
                return ResourceManager.GetString("ClefElement_TAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arranger.
        /// </summary>
        internal static string CreatorElementType_Arranger {
            get {
                return ResourceManager.GetString("CreatorElementType_Arranger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composer.
        /// </summary>
        internal static string CreatorElementType_Composer {
            get {
                return ResourceManager.GetString("CreatorElementType_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyricist.
        /// </summary>
        internal static string CreatorElementType_Lyricist {
            get {
                return ResourceManager.GetString("CreatorElementType_Lyricist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poet.
        /// </summary>
        internal static string CreatorElementType_Poet {
            get {
                return ResourceManager.GetString("CreatorElementType_Poet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string CreatorElementType_Unknown {
            get {
                return ResourceManager.GetString("CreatorElementType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discontinue.
        /// </summary>
        internal static string EndingElement_Discontinue {
            get {
                return ResourceManager.GetString("EndingElement_Discontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string EndingElement_Start {
            get {
                return ResourceManager.GetString("EndingElement_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string EndingElement_Stop {
            get {
                return ResourceManager.GetString("EndingElement_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string EndingElement_Undefined {
            get {
                return ResourceManager.GetString("EndingElement_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string EventDescription_tempo {
            get {
                return ResourceManager.GetString("EventDescription_tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted Fermata.
        /// </summary>
        internal static string FermataElement_Inverted {
            get {
                return ResourceManager.GetString("FermataElement_Inverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermata.
        /// </summary>
        internal static string FermataElement_Upright {
            get {
                return ResourceManager.GetString("FermataElement_Upright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glissando.
        /// </summary>
        internal static string GlissandoElement_Name {
            get {
                return ResourceManager.GetString("GlissandoElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyElement_key {
            get {
                return ResourceManager.GetString("KeyElement_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to major.
        /// </summary>
        internal static string KeyElement_major {
            get {
                return ResourceManager.GetString("KeyElement_major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor.
        /// </summary>
        internal static string KeyElement_minor {
            get {
                return ResourceManager.GetString("KeyElement_minor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128th.
        /// </summary>
        internal static string NoteElement_128th {
            get {
                return ResourceManager.GetString("NoteElement_128th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th.
        /// </summary>
        internal static string NoteElement_16th {
            get {
                return ResourceManager.GetString("NoteElement_16th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th rest.
        /// </summary>
        internal static string NoteElement_16th_rest {
            get {
                return ResourceManager.GetString("NoteElement_16th_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256th.
        /// </summary>
        internal static string NoteElement_256th {
            get {
                return ResourceManager.GetString("NoteElement_256th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32nd.
        /// </summary>
        internal static string NoteElement_32nd {
            get {
                return ResourceManager.GetString("NoteElement_32nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32nd rest.
        /// </summary>
        internal static string NoteElement_32nd_rest {
            get {
                return ResourceManager.GetString("NoteElement_32nd_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64th.
        /// </summary>
        internal static string NoteElement_64th {
            get {
                return ResourceManager.GetString("NoteElement_64th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64th_rest.
        /// </summary>
        internal static string NoteElement_64th_rest {
            get {
                return ResourceManager.GetString("NoteElement_64th_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breve.
        /// </summary>
        internal static string NoteElement_breve {
            get {
                return ResourceManager.GetString("NoteElement_breve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotted.
        /// </summary>
        internal static string NoteElement_dotted {
            get {
                return ResourceManager.GetString("NoteElement_dotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string NoteElement_eight {
            get {
                return ResourceManager.GetString("NoteElement_eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight rest.
        /// </summary>
        internal static string NoteElement_eight_rest {
            get {
                return ResourceManager.GetString("NoteElement_eight_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half.
        /// </summary>
        internal static string NoteElement_half {
            get {
                return ResourceManager.GetString("NoteElement_half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half rest.
        /// </summary>
        internal static string NoteElement_half_rest {
            get {
                return ResourceManager.GetString("NoteElement_half_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string NoteElement_longus {
            get {
                return ResourceManager.GetString("NoteElement_longus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxima.
        /// </summary>
        internal static string NoteElement_maxima {
            get {
                return ResourceManager.GetString("NoteElement_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full measure.
        /// </summary>
        internal static string NoteElement_measure {
            get {
                return ResourceManager.GetString("NoteElement_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full measure rest.
        /// </summary>
        internal static string NoteElement_measure_rest {
            get {
                return ResourceManager.GetString("NoteElement_measure_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string NoteElement_measure_text {
            get {
                return ResourceManager.GetString("NoteElement_measure_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarter.
        /// </summary>
        internal static string NoteElement_quarter {
            get {
                return ResourceManager.GetString("NoteElement_quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarter rest.
        /// </summary>
        internal static string NoteElement_quarter_rest {
            get {
                return ResourceManager.GetString("NoteElement_quarter_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tie start.
        /// </summary>
        internal static string NoteElement_tie_start {
            get {
                return ResourceManager.GetString("NoteElement_tie_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tie end.
        /// </summary>
        internal static string NoteElement_tie_stop {
            get {
                return ResourceManager.GetString("NoteElement_tie_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string NoteElement_unknown {
            get {
                return ResourceManager.GetString("NoteElement_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown rest.
        /// </summary>
        internal static string NoteElement_unknown_rest {
            get {
                return ResourceManager.GetString("NoteElement_unknown_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified rest.
        /// </summary>
        internal static string NoteElement_unspecified_rest {
            get {
                return ResourceManager.GetString("NoteElement_unspecified_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole.
        /// </summary>
        internal static string NoteElement_whole {
            get {
                return ResourceManager.GetString("NoteElement_whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole rest.
        /// </summary>
        internal static string NoteElement_whole_rest {
            get {
                return ResourceManager.GetString("NoteElement_whole_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled.
        /// </summary>
        internal static string NoteHeadElement_Filled {
            get {
                return ResourceManager.GetString("NoteHeadElement_Filled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parentheses.
        /// </summary>
        internal static string NoteHeadElement_Parentheses {
            get {
                return ResourceManager.GetString("NoteHeadElement_Parentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string PartElement_Name {
            get {
                return ResourceManager.GetString("PartElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This partlist contains.
        /// </summary>
        internal static string PartListElement_Message {
            get {
                return ResourceManager.GetString("PartListElement_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string PartListElement_Part {
            get {
                return ResourceManager.GetString("PartListElement_Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string PartListElement_Parts {
            get {
                return ResourceManager.GetString("PartListElement_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string PitchElement_a {
            get {
                return ResourceManager.GetString("PitchElement_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-flat.
        /// </summary>
        internal static string PitchElement_aFlat {
            get {
                return ResourceManager.GetString("PitchElement_aFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-sharp.
        /// </summary>
        internal static string PitchElement_aSharp {
            get {
                return ResourceManager.GetString("PitchElement_aSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string PitchElement_b {
            get {
                return ResourceManager.GetString("PitchElement_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-flat.
        /// </summary>
        internal static string PitchElement_Bb {
            get {
                return ResourceManager.GetString("PitchElement_Bb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string PitchElement_c {
            get {
                return ResourceManager.GetString("PitchElement_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-flat.
        /// </summary>
        internal static string PitchElement_cFlat {
            get {
                return ResourceManager.GetString("PitchElement_cFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-sharp.
        /// </summary>
        internal static string PitchElement_cSharp {
            get {
                return ResourceManager.GetString("PitchElement_cSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string PitchElement_d {
            get {
                return ResourceManager.GetString("PitchElement_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-flat.
        /// </summary>
        internal static string PitchElement_dFlat {
            get {
                return ResourceManager.GetString("PitchElement_dFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-sharp.
        /// </summary>
        internal static string PitchElement_dSharp {
            get {
                return ResourceManager.GetString("PitchElement_dSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string PitchElement_e {
            get {
                return ResourceManager.GetString("PitchElement_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-flat.
        /// </summary>
        internal static string PitchElement_eFlat {
            get {
                return ResourceManager.GetString("PitchElement_eFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-sharp.
        /// </summary>
        internal static string PitchElement_eSharp {
            get {
                return ResourceManager.GetString("PitchElement_eSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string PitchElement_f {
            get {
                return ResourceManager.GetString("PitchElement_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-sharp.
        /// </summary>
        internal static string PitchElement_fSharp {
            get {
                return ResourceManager.GetString("PitchElement_fSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string PitchElement_g {
            get {
                return ResourceManager.GetString("PitchElement_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-flat.
        /// </summary>
        internal static string PitchElement_gFlat {
            get {
                return ResourceManager.GetString("PitchElement_gFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-sharp.
        /// </summary>
        internal static string PitchElement_gSharp {
            get {
                return ResourceManager.GetString("PitchElement_gSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string PitctElement_g {
            get {
                return ResourceManager.GetString("PitctElement_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backward.
        /// </summary>
        internal static string RepeatElement_Backward {
            get {
                return ResourceManager.GetString("RepeatElement_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward.
        /// </summary>
        internal static string RepeatElement_Forward {
            get {
                return ResourceManager.GetString("RepeatElement_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        internal static string RepeatElement_Name {
            get {
                return ResourceManager.GetString("RepeatElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string RestElement_Name {
            get {
                return ResourceManager.GetString("RestElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        internal static string SlideElement_Name {
            get {
                return ResourceManager.GetString("SlideElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legato.
        /// </summary>
        internal static string SlurElement_Name {
            get {
                return ResourceManager.GetString("SlurElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempo.
        /// </summary>
        internal static string SoundElement_Tempo {
            get {
                return ResourceManager.GetString("SoundElement_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        internal static string StartStopContinueElement_Continue {
            get {
                return ResourceManager.GetString("StartStopContinueElement_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string StartStopContinueElement_Start {
            get {
                return ResourceManager.GetString("StartStopContinueElement_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        internal static string StartStopContinueElement_Stop {
            get {
                return ResourceManager.GetString("StartStopContinueElement_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undefined.
        /// </summary>
        internal static string StartStopContinueElement_Undefined {
            get {
                return ResourceManager.GetString("StartStopContinueElement_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tie.
        /// </summary>
        internal static string TiedElement_Name {
            get {
                return ResourceManager.GetString("TiedElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eights.
        /// </summary>
        internal static string TimeElement_eights {
            get {
                return ResourceManager.GetString("TimeElement_eights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to halves.
        /// </summary>
        internal static string TimeElement_halves {
            get {
                return ResourceManager.GetString("TimeElement_halves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        internal static string TimeElement_pulse {
            get {
                return ResourceManager.GetString("TimeElement_pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarters.
        /// </summary>
        internal static string TimeElement_quarters {
            get {
                return ResourceManager.GetString("TimeElement_quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sixteenths.
        /// </summary>
        internal static string TimeElement_sixteenths {
            get {
                return ResourceManager.GetString("TimeElement_sixteenths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thirtyseconds.
        /// </summary>
        internal static string TimeElement_thirtyseconds {
            get {
                return ResourceManager.GetString("TimeElement_thirtyseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wholes.
        /// </summary>
        internal static string TimeElement_wholes {
            get {
                return ResourceManager.GetString("TimeElement_wholes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonies.
        /// </summary>
        internal static string UserSettings_BrailleNames_Harmonies {
            get {
                return ResourceManager.GetString("UserSettings_BrailleNames_Harmonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Numbers.
        /// </summary>
        internal static string UserSettings_BrailleNames_MeasureNumbers {
            get {
                return ResourceManager.GetString("UserSettings_BrailleNames_MeasureNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notations.
        /// </summary>
        internal static string UserSettings_BrailleNames_Notations {
            get {
                return ResourceManager.GetString("UserSettings_BrailleNames_Notations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string UserSettings_BrailleNames_Notes {
            get {
                return ResourceManager.GetString("UserSettings_BrailleNames_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats.
        /// </summary>
        internal static string UserSettings_PlayerNames_Beats {
            get {
                return ResourceManager.GetString("UserSettings_PlayerNames_Beats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonies.
        /// </summary>
        internal static string UserSettings_PlayerNames_Harmonies {
            get {
                return ResourceManager.GetString("UserSettings_PlayerNames_Harmonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        internal static string UserSettings_ReaderNames_Divisions {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_Divisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Events.
        /// </summary>
        internal static string UserSettings_ReaderNames_EndEvents {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_EndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonies.
        /// </summary>
        internal static string UserSettings_ReaderNames_Harmonies {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_Harmonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmony Codes.
        /// </summary>
        internal static string UserSettings_ReaderNames_HarmonyCodes {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_HarmonyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure numbers.
        /// </summary>
        internal static string UserSettings_ReaderNames_MeasureNumbers {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_MeasureNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notationer.
        /// </summary>
        internal static string UserSettings_ReaderNames_Notations {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_Notations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string UserSettings_ReaderNames_Notes {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Values.
        /// </summary>
        internal static string UserSettings_ReaderNames_NoteValues {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_NoteValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktaver.
        /// </summary>
        internal static string UserSettings_ReaderNames_Octaves {
            get {
                return ResourceManager.GetString("UserSettings_ReaderNames_Octaves", resourceCulture);
            }
        }
    }
}
