//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReaderModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReaderModel.ResourcesForModel", typeof(ResourcesForModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 128th.
        /// </summary>
        internal static string NoteElement_128th {
            get {
                return ResourceManager.GetString("NoteElement_128th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th.
        /// </summary>
        internal static string NoteElement_16th {
            get {
                return ResourceManager.GetString("NoteElement_16th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16th rest.
        /// </summary>
        internal static string NoteElement_16th_rest {
            get {
                return ResourceManager.GetString("NoteElement_16th_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 256th.
        /// </summary>
        internal static string NoteElement_256th {
            get {
                return ResourceManager.GetString("NoteElement_256th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32nd.
        /// </summary>
        internal static string NoteElement_32nd {
            get {
                return ResourceManager.GetString("NoteElement_32nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32nd rest.
        /// </summary>
        internal static string NoteElement_32nd_rest {
            get {
                return ResourceManager.GetString("NoteElement_32nd_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64th.
        /// </summary>
        internal static string NoteElement_64th {
            get {
                return ResourceManager.GetString("NoteElement_64th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 64th_rest.
        /// </summary>
        internal static string NoteElement_64th_rest {
            get {
                return ResourceManager.GetString("NoteElement_64th_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breve.
        /// </summary>
        internal static string NoteElement_breve {
            get {
                return ResourceManager.GetString("NoteElement_breve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dotted.
        /// </summary>
        internal static string NoteElement_dotted {
            get {
                return ResourceManager.GetString("NoteElement_dotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight.
        /// </summary>
        internal static string NoteElement_eight {
            get {
                return ResourceManager.GetString("NoteElement_eight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eight rest.
        /// </summary>
        internal static string NoteElement_eight_rest {
            get {
                return ResourceManager.GetString("NoteElement_eight_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half.
        /// </summary>
        internal static string NoteElement_half {
            get {
                return ResourceManager.GetString("NoteElement_half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half rest.
        /// </summary>
        internal static string NoteElement_half_rest {
            get {
                return ResourceManager.GetString("NoteElement_half_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to long.
        /// </summary>
        internal static string NoteElement_longus {
            get {
                return ResourceManager.GetString("NoteElement_longus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxima.
        /// </summary>
        internal static string NoteElement_maxima {
            get {
                return ResourceManager.GetString("NoteElement_maxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full measure.
        /// </summary>
        internal static string NoteElement_measure {
            get {
                return ResourceManager.GetString("NoteElement_measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full measure rest.
        /// </summary>
        internal static string NoteElement_measure_rest {
            get {
                return ResourceManager.GetString("NoteElement_measure_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure.
        /// </summary>
        internal static string NoteElement_measure_text {
            get {
                return ResourceManager.GetString("NoteElement_measure_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarter.
        /// </summary>
        internal static string NoteElement_quarter {
            get {
                return ResourceManager.GetString("NoteElement_quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quarter rest.
        /// </summary>
        internal static string NoteElement_quarter_rest {
            get {
                return ResourceManager.GetString("NoteElement_quarter_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tie start.
        /// </summary>
        internal static string NoteElement_tie_start {
            get {
                return ResourceManager.GetString("NoteElement_tie_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tie end.
        /// </summary>
        internal static string NoteElement_tie_stop {
            get {
                return ResourceManager.GetString("NoteElement_tie_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string NoteElement_unknown {
            get {
                return ResourceManager.GetString("NoteElement_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown rest.
        /// </summary>
        internal static string NoteElement_unknown_rest {
            get {
                return ResourceManager.GetString("NoteElement_unknown_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unspecified rest.
        /// </summary>
        internal static string NoteElement_unspecified_rest {
            get {
                return ResourceManager.GetString("NoteElement_unspecified_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole.
        /// </summary>
        internal static string NoteElement_whole {
            get {
                return ResourceManager.GetString("NoteElement_whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whole rest.
        /// </summary>
        internal static string NoteElement_whole_rest {
            get {
                return ResourceManager.GetString("NoteElement_whole_rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string PitchElement_a {
            get {
                return ResourceManager.GetString("PitchElement_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-flat.
        /// </summary>
        internal static string PitchElement_aFlat {
            get {
                return ResourceManager.GetString("PitchElement_aFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-sharp.
        /// </summary>
        internal static string PitchElement_aSharp {
            get {
                return ResourceManager.GetString("PitchElement_aSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string PitchElement_b {
            get {
                return ResourceManager.GetString("PitchElement_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-flat.
        /// </summary>
        internal static string PitchElement_Bb {
            get {
                return ResourceManager.GetString("PitchElement_Bb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string PitchElement_c {
            get {
                return ResourceManager.GetString("PitchElement_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-flat.
        /// </summary>
        internal static string PitchElement_cFlat {
            get {
                return ResourceManager.GetString("PitchElement_cFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C-sharp.
        /// </summary>
        internal static string PitchElement_cSharp {
            get {
                return ResourceManager.GetString("PitchElement_cSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string PitchElement_d {
            get {
                return ResourceManager.GetString("PitchElement_d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-flat.
        /// </summary>
        internal static string PitchElement_dFlat {
            get {
                return ResourceManager.GetString("PitchElement_dFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-sharp.
        /// </summary>
        internal static string PitchElement_dSharp {
            get {
                return ResourceManager.GetString("PitchElement_dSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string PitchElement_e {
            get {
                return ResourceManager.GetString("PitchElement_e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-flat.
        /// </summary>
        internal static string PitchElement_eFlat {
            get {
                return ResourceManager.GetString("PitchElement_eFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-sharp.
        /// </summary>
        internal static string PitchElement_eSharp {
            get {
                return ResourceManager.GetString("PitchElement_eSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string PitchElement_f {
            get {
                return ResourceManager.GetString("PitchElement_f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F-sharp.
        /// </summary>
        internal static string PitchElement_fSharp {
            get {
                return ResourceManager.GetString("PitchElement_fSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string PitchElement_g {
            get {
                return ResourceManager.GetString("PitchElement_g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-flat.
        /// </summary>
        internal static string PitchElement_gFlat {
            get {
                return ResourceManager.GetString("PitchElement_gFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-sharp.
        /// </summary>
        internal static string PitchElement_gSharp {
            get {
                return ResourceManager.GetString("PitchElement_gSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string PitctElement_g {
            get {
                return ResourceManager.GetString("PitctElement_g", resourceCulture);
            }
        }
    }
}
