using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MusicXmlReader
{
    public class LocalizationAnalysis
    {
        /// <summary>
        /// Exclusively for use by analysis of Localization-resources:
        /// Allows access to the internal (Autogenerated) method ResourcesForBrailleMusicDecoder as a public method
        /// </summary>
        /// <returns></returns>
        public static object GetLocalizationClass()
        {
#warning todo: Return a list of objects instead of just one
            return new ResourcesForUI(); 
        }
    }
}
