//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReader.ResourcesForUI", typeof(ResourcesForUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing.
        /// </summary>
        internal static string ButtonStart_StartPlaying {
            get {
                return ResourceManager.GetString("ButtonStart_StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing.
        /// </summary>
        internal static string ButtonStart_StopPlaying {
            get {
                return ResourceManager.GetString("ButtonStart_StopPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBOS MusicReader.
        /// </summary>
        internal static string MainForm_ApplicationName {
            get {
                return ResourceManager.GetString("MainForm_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to unsupported screenreader.
        /// </summary>
        internal static string Message_ConnectedToNonDefaultScreenReader {
            get {
                return ResourceManager.GetString("Message_ConnectedToNonDefaultScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string Message_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Message_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to screenreader.
        /// </summary>
        internal static string Message_FailedToConnectToScreenReader {
            get {
                return ResourceManager.GetString("Message_FailedToConnectToScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read MusicXml file.
        /// </summary>
        internal static string Message_FailedToReadMusicXmlFile {
            get {
                return ResourceManager.GetString("Message_FailedToReadMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start program.
        /// </summary>
        internal static string Message_FailedToStartProgram {
            get {
                return ResourceManager.GetString("Message_FailedToStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string Message_FileNotFound {
            get {
                return ResourceManager.GetString("Message_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program may not work as expected.
        /// </summary>
        internal static string Message_MayNotWorkAsExpected {
            get {
                return ResourceManager.GetString("Message_MayNotWorkAsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing program file.
        /// </summary>
        internal static string Message_MissingProgramFile {
            get {
                return ResourceManager.GetString("Message_MissingProgramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see Log File (Tools-&gt;Log File).
        /// </summary>
        internal static string Message_PleaseSeeLogFile {
            get {
                return ResourceManager.GetString("Message_PleaseSeeLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Undefined Message).
        /// </summary>
        internal static string Message_UndefinedMessage {
            get {
                return ResourceManager.GetString("Message_UndefinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MusicXml file was specified .
        /// </summary>
        internal static string Message_UnspecifiedMusicXmlFile {
            get {
                return ResourceManager.GetString("Message_UnspecifiedMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml files.
        /// </summary>
        internal static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read.
        /// </summary>
        internal static string TextBox_Messages_FailedToRead_File {
            get {
                return ResourceManager.GetString("TextBox_Messages_FailedToRead_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string TextBox_Messages_Reading_File {
            get {
                return ResourceManager.GetString("TextBox_Messages_Reading_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is exiting.
        /// </summary>
        internal static string TextBox_Messages_TheProgramIsExiting {
            get {
                return ResourceManager.GetString("TextBox_Messages_TheProgramIsExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string ToolStripMenuItem_Edit {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Files.
        /// </summary>
        internal static string ToolStripMenuItem_Files {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exit.
        /// </summary>
        internal static string ToolStripMenuItem_Files_Exit {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open MusicXml File.
        /// </summary>
        internal static string ToolStripMenuItem_Files_OpenMusicXmlFile {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_OpenMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string ToolStripMenuItem_Help {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string ToolStripMenuItem_Tools {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file  as raw &amp;Xml.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_InspectAsXml {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_InspectAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Log file.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Logfile {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file location.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Logfile_Location {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Logfile_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;MuseScore.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_MuseScore {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_MuseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file location.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_OpenXmlFileLocation {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_OpenXmlFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as &amp;text.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_SaveAsText {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_SaveAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sibelius.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Sibelius {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Sibelius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file as &amp;interpreted Xml.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_ViewAsInterpretedXml {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_ViewAsInterpretedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string ToolStripMenuItem_View {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All filter items.
        /// </summary>
        internal static string TreeView_All_Items {
            get {
                return ResourceManager.GetString("TreeView_All_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille Music representation.
        /// </summary>
        internal static string TreeView_MusicAsBraille {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TreeView_MusicAsBraille_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string TreeView_MusicAsBraille_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music playback.
        /// </summary>
        internal static string TreeView_MusicAsSound {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TreeView_MusicAsSound_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string TreeView_MusicAsSound_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text representation.
        /// </summary>
        internal static string TreeView_MusicAsSpeech {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TreeView_MusicAsSpeech_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string TreeView_MusicAsSpeech_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter items.
        /// </summary>
        internal static string TreeWiew_Items {
            get {
                return ResourceManager.GetString("TreeWiew_Items", resourceCulture);
            }
        }
    }
}
