//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReader.ResourcesForUI", typeof(ResourcesForUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing.
        /// </summary>
        internal static string ButtonStart_StartPlaying {
            get {
                return ResourceManager.GetString("ButtonStart_StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing.
        /// </summary>
        internal static string ButtonStart_StopPlaying {
            get {
                return ResourceManager.GetString("ButtonStart_StopPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string DirectoryNames_CultureString {
            get {
                return ResourceManager.GetString("DirectoryNames_CultureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml downloads.
        /// </summary>
        internal static string DirectoryNames_Downloads {
            get {
                return ResourceManager.GetString("DirectoryNames_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        internal static string DirectoryNames_Samples {
            get {
                return ResourceManager.GetString("DirectoryNames_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s manual.doc.
        /// </summary>
        internal static string FileNames_UsersManual {
            get {
                return ResourceManager.GetString("FileNames_UsersManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No details found.
        /// </summary>
        internal static string ListBoxDetails_NoDetailsFound {
            get {
                return ResourceManager.GetString("ListBoxDetails_NoDetailsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note list.
        /// </summary>
        internal static string ListView_Accessible_Name {
            get {
                return ResourceManager.GetString("ListView_Accessible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBOS MusicReader.
        /// </summary>
        internal static string MainForm_ApplicationName {
            get {
                return ResourceManager.GetString("MainForm_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to unsupported screenreader.
        /// </summary>
        internal static string Message_ConnectedToNonDefaultScreenReader {
            get {
                return ResourceManager.GetString("Message_ConnectedToNonDefaultScreenReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found.
        /// </summary>
        internal static string Message_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Message_DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit the program?.
        /// </summary>
        internal static string Message_DoYouWantToExitTheProgram {
            get {
                return ResourceManager.GetString("Message_DoYouWantToExitTheProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read MusicXml file.
        /// </summary>
        internal static string Message_FailedToReadMusicXmlFile {
            get {
                return ResourceManager.GetString("Message_FailedToReadMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to show.
        /// </summary>
        internal static string Message_FailedToShow {
            get {
                return ResourceManager.GetString("Message_FailedToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start program.
        /// </summary>
        internal static string Message_FailedToStartProgram {
            get {
                return ResourceManager.GetString("Message_FailedToStartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string Message_FileNotFound {
            get {
                return ResourceManager.GetString("Message_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAWS screenreader is not running.
        /// </summary>
        internal static string Message_JAWSScreenReaderIsNotRunning {
            get {
                return ResourceManager.GetString("Message_JAWSScreenReaderIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location of file could not be determined.
        /// </summary>
        internal static string Message_LocationNotDetermined {
            get {
                return ResourceManager.GetString("Message_LocationNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program may not work as expected.
        /// </summary>
        internal static string Message_MayNotWorkAsExpected {
            get {
                return ResourceManager.GetString("Message_MayNotWorkAsExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing program file.
        /// </summary>
        internal static string Message_MissingProgramFile {
            get {
                return ResourceManager.GetString("Message_MissingProgramFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed while playing music.
        /// </summary>
        internal static string Message_NotAllowedWhilePlaying {
            get {
                return ResourceManager.GetString("Message_NotAllowedWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see Log File (Tools-&gt;Log File).
        /// </summary>
        internal static string Message_PleaseSeeLogFile {
            get {
                return ResourceManager.GetString("Message_PleaseSeeLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop plaing first.
        /// </summary>
        internal static string Message_StopPlayingFirst {
            get {
                return ResourceManager.GetString("Message_StopPlayingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Undefined Message).
        /// </summary>
        internal static string Message_UndefinedMessage {
            get {
                return ResourceManager.GetString("Message_UndefinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during program initialization.
        /// </summary>
        internal static string Message_UnspecifiedInitializationError {
            get {
                return ResourceManager.GetString("Message_UnspecifiedInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MusicXml file was specified .
        /// </summary>
        internal static string Message_UnspecifiedMusicXmlFile {
            get {
                return ResourceManager.GetString("Message_UnspecifiedMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml files.
        /// </summary>
        internal static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed MusicXml files.
        /// </summary>
        internal static string OpenFileDialog_Filter_mxl {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter_mxl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Go to measure.
        /// </summary>
        internal static string ParameterInputForm_GoTo {
            get {
                return ResourceManager.GetString("ParameterInputForm_GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of &amp;Normal tempo.
        /// </summary>
        internal static string ParameterInputForm_PctOfNominalTempo {
            get {
                return ResourceManager.GetString("ParameterInputForm_PctOfNominalTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Repeat measures.
        /// </summary>
        internal static string ParameterInputForm_Repeat {
            get {
                return ResourceManager.GetString("ParameterInputForm_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourcesForUI.resx.
        /// </summary>
        internal static string ResourceFileName {
            get {
                return ResourceManager.GetString("ResourceFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select downloaded files for import.
        /// </summary>
        internal static string SelectFileDialog_Title {
            get {
                return ResourceManager.GetString("SelectFileDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string Status_file {
            get {
                return ResourceManager.GetString("Status_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string Status_files {
            get {
                return ResourceManager.GetString("Status_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported.
        /// </summary>
        internal static string Status_Imported {
            get {
                return ResourceManager.GetString("Status_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing sample files.
        /// </summary>
        internal static string Status_ImportingSampleFiles {
            get {
                return ResourceManager.GetString("Status_ImportingSampleFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing selected files.
        /// </summary>
        internal static string Status_ImportingSelectedFiles {
            get {
                return ResourceManager.GetString("Status_ImportingSelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status line.
        /// </summary>
        internal static string StatusLine_Accessible_Name {
            get {
                return ResourceManager.GetString("StatusLine_Accessible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert.
        /// </summary>
        internal static string TextBox_Messages_FailedToConvert_File {
            get {
                return ResourceManager.GetString("TextBox_Messages_FailedToConvert_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read.
        /// </summary>
        internal static string TextBox_Messages_FailedToRead_File {
            get {
                return ResourceManager.GetString("TextBox_Messages_FailedToRead_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        internal static string TextBox_Messages_Reading_File {
            get {
                return ResourceManager.GetString("TextBox_Messages_Reading_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program is exiting.
        /// </summary>
        internal static string TextBox_Messages_TheProgramIsExiting {
            get {
                return ResourceManager.GetString("TextBox_Messages_TheProgramIsExiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to MusicXml (.xml).
        /// </summary>
        internal static string TextBox_Messages_ToMusicXml {
            get {
                return ResourceManager.GetString("TextBox_Messages_ToMusicXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format.
        /// </summary>
        internal static string TextBox_Messages_UnsupportedFileFormat {
            get {
                return ResourceManager.GetString("TextBox_Messages_UnsupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Note-archives.
        /// </summary>
        internal static string ToolsStripMenuItem_Archives {
            get {
                return ResourceManager.GetString("ToolsStripMenuItem_Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Instrument details.
        /// </summary>
        internal static string ToolsStripMenuItem_View_Instruments {
            get {
                return ResourceManager.GetString("ToolsStripMenuItem_View_Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string ToolStripMenuItem_Edit {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Files.
        /// </summary>
        internal static string ToolStripMenuItem_Files {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string ToolStripMenuItem_Files_Exit {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp;downloads.
        /// </summary>
        internal static string ToolStripMenuItem_Files_ImportDownloads {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_ImportDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp;todays downloads.
        /// </summary>
        internal static string ToolStripMenuItem_Files_ImportNewestDownloads {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_ImportNewestDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import newest &amp;samples.
        /// </summary>
        internal static string ToolStripMenuItem_Files_ImportNewestSamples {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_ImportNewestSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open MusicXml File.
        /// </summary>
        internal static string ToolStripMenuItem_Files_OpenMusicXmlFile {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Files_OpenMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string ToolStripMenuItem_Help {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string ToolStripMenuItem_Help_About {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string ToolStripMenuItem_Help_About_Version {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Keyboard shortcuts.
        /// </summary>
        internal static string ToolStripMenuItem_Help_Shortcuts {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;user&apos;s manual.
        /// </summary>
        internal static string ToolStripMenuItem_Help_ShowUsersManual {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_ShowUsersManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to newest &amp;software.
        /// </summary>
        internal static string ToolStripMenuItem_Help_SoftwareUpdate {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.ibos.dk/hjaelpemidler/ibos-nodelaeser.html.
        /// </summary>
        internal static string ToolStripMenuItem_Help_SoftwareUpdateLink {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Help_SoftwareUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tools.
        /// </summary>
        internal static string ToolStripMenuItem_Tools {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file  as raw &amp;Xml.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_InspectAsXml {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_InspectAsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;JAWS settings.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_JAWS_Settings {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_JAWS_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Log file.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Logfile {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file location.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Logfile_Location {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Logfile_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;MuseScore.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_MuseScore {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_MuseScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file location.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_OpenXmlFileLocation {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_OpenXmlFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as &amp;text.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_SaveAsText {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_SaveAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sibelius.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_Sibelius {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_Sibelius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicXml file as &amp;interpreted Xml.
        /// </summary>
        internal static string ToolStripMenuItem_Tools_ViewAsInterpretedXml {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_Tools_ViewAsInterpretedXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        internal static string ToolStripMenuItem_View {
            get {
                return ResourceManager.GetString("ToolStripMenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note filter.
        /// </summary>
        internal static string TreeView_Accessible_Name {
            get {
                return ResourceManager.GetString("TreeView_Accessible_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;All filter items.
        /// </summary>
        internal static string TreeView_All_Items {
            get {
                return ResourceManager.GetString("TreeView_All_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;1: Check all.
        /// </summary>
        internal static string TreeView_CheckAll {
            get {
                return ResourceManager.GetString("TreeView_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string Treeview_for {
            get {
                return ResourceManager.GetString("Treeview_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Braille Music representation.
        /// </summary>
        internal static string TreeView_MusicAsBraille {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details.
        /// </summary>
        internal static string TreeView_MusicAsBraille_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Parts.
        /// </summary>
        internal static string TreeView_MusicAsBraille_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsBraille_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Music playback.
        /// </summary>
        internal static string TreeView_MusicAsSound {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details.
        /// </summary>
        internal static string TreeView_MusicAsSound_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Parts.
        /// </summary>
        internal static string TreeView_MusicAsSound_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSound_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Text representation.
        /// </summary>
        internal static string TreeView_MusicAsSpeech {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Details.
        /// </summary>
        internal static string TreeView_MusicAsSpeech_Details {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Parts.
        /// </summary>
        internal static string TreeView_MusicAsSpeech_Parts {
            get {
                return ResourceManager.GetString("TreeView_MusicAsSpeech_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;0: Uncheck all.
        /// </summary>
        internal static string TreeView_UncheckAll {
            get {
                return ResourceManager.GetString("TreeView_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Filter items.
        /// </summary>
        internal static string TreeWiew_Items {
            get {
                return ResourceManager.GetString("TreeWiew_Items", resourceCulture);
            }
        }
    }
}
