//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReader.ResourcesForSettings", typeof(ResourcesForSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Braille_ {
            get {
                return ResourceManager.GetString("Braille_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser program location.
        /// </summary>
        internal static string Braille_ApplicationLocation {
            get {
                return ResourceManager.GetString("Braille_ApplicationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser program name.
        /// </summary>
        internal static string Braille_ApplicationName {
            get {
                return ResourceManager.GetString("Braille_ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille file format.
        /// </summary>
        internal static string Braille_BrailleFileFormat {
            get {
                return ResourceManager.GetString("Braille_BrailleFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser escapesequence.
        /// </summary>
        internal static string Braille_EmbosserEscapeSequence {
            get {
                return ResourceManager.GetString("Braille_EmbosserEscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser name.
        /// </summary>
        internal static string Braille_EmbosserName {
            get {
                return ResourceManager.GetString("Braille_EmbosserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser  program location.
        /// </summary>
        internal static string Braille_EmbosserProgramLocation {
            get {
                return ResourceManager.GetString("Braille_EmbosserProgramLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser program name.
        /// </summary>
        internal static string Braille_EmbosserProgramName {
            get {
                return ResourceManager.GetString("Braille_EmbosserProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embosser profile.
        /// </summary>
        internal static string Braille_EmbosserSettingsCaption {
            get {
                return ResourceManager.GetString("Braille_EmbosserSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape sequence.
        /// </summary>
        internal static string Braille_EscapeSequence {
            get {
                return ResourceManager.GetString("Braille_EscapeSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII.
        /// </summary>
        internal static string Braille_FileFormatASCII {
            get {
                return ResourceManager.GetString("Braille_FileFormatASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OctoBraille 1252.
        /// </summary>
        internal static string Braille_FileFormatOctoBraille1252 {
            get {
                return ResourceManager.GetString("Braille_FileFormatOctoBraille1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        internal static string Braille_GenericDeviceName {
            get {
                return ResourceManager.GetString("Braille_GenericDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic Braille device settings.
        /// </summary>
        internal static string Braille_GenericSettingsCaption {
            get {
                return ResourceManager.GetString("Braille_GenericSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BANA 2015 layout.
        /// </summary>
        internal static string Braille_LayoutBANA {
            get {
                return ResourceManager.GetString("Braille_LayoutBANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBOS/Refsnæs layout.
        /// </summary>
        internal static string Braille_LayoutIBOS {
            get {
                return ResourceManager.GetString("Braille_LayoutIBOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notetaker name.
        /// </summary>
        internal static string Braille_NotetakerName {
            get {
                return ResourceManager.GetString("Braille_NotetakerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notetaker profile.
        /// </summary>
        internal static string Braille_NoteTakerSettingsCaption {
            get {
                return ResourceManager.GetString("Braille_NoteTakerSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille page height.
        /// </summary>
        internal static string Braille_PageHeight {
            get {
                return ResourceManager.GetString("Braille_PageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille page layout.
        /// </summary>
        internal static string Braille_PageLayout {
            get {
                return ResourceManager.GetString("Braille_PageLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braille page width.
        /// </summary>
        internal static string Braille_PageWidth {
            get {
                return ResourceManager.GetString("Braille_PageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEF.
        /// </summary>
        internal static string Braille_PEF {
            get {
                return ResourceManager.GetString("Braille_PEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode.
        /// </summary>
        internal static string Braille_Unicode {
            get {
                return ResourceManager.GetString("Braille_Unicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode(UTF-16).
        /// </summary>
        internal static string Braille_UnicodeUtf16 {
            get {
                return ResourceManager.GetString("Braille_UnicodeUtf16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode(UTF-32).
        /// </summary>
        internal static string Braille_UnicodeUtf32 {
            get {
                return ResourceManager.GetString("Braille_UnicodeUtf32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicode(UTF-8).
        /// </summary>
        internal static string Braille_UnicodeUtf8 {
            get {
                return ResourceManager.GetString("Braille_UnicodeUtf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capella location.
        /// </summary>
        internal static string General_CapellaLocation {
            get {
                return ResourceManager.GetString("General_CapellaLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal profile.
        /// </summary>
        internal static string General_Caption {
            get {
                return ResourceManager.GetString("General_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Braille Music directory.
        /// </summary>
        internal static string General_LatestBrailleMusicDirectory {
            get {
                return ResourceManager.GetString("General_LatestBrailleMusicDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest MusicXml file.
        /// </summary>
        internal static string General_LatestMusicXmlFile {
            get {
                return ResourceManager.GetString("General_LatestMusicXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest MusicXml directory.
        /// </summary>
        internal static string General_LatestMusicXmlPath {
            get {
                return ResourceManager.GetString("General_LatestMusicXmlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MuseScore location.
        /// </summary>
        internal static string General_MuseScoreLocation {
            get {
                return ResourceManager.GetString("General_MuseScoreLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibelius location.
        /// </summary>
        internal static string General_SibeliusLocation {
            get {
                return ResourceManager.GetString("General_SibeliusLocation", resourceCulture);
            }
        }
    }
}
