//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicXmlReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicXmlReader.ResourcesForHelp", typeof(ResourcesForHelp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Conjunction_Or {
            get {
                return ResourceManager.GetString("Conjunction_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARROW-DOWN.
        /// </summary>
        internal static string Shortcut_ArrowDown {
            get {
                return ResourceManager.GetString("Shortcut_ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARROW-LEFT.
        /// </summary>
        internal static string Shortcut_ArrowLeft {
            get {
                return ResourceManager.GetString("Shortcut_ArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARROW-RIGHT.
        /// </summary>
        internal static string Shortcut_ArrowRight {
            get {
                return ResourceManager.GetString("Shortcut_ArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARROW-UP.
        /// </summary>
        internal static string Shortcut_ArrowUp {
            get {
                return ResourceManager.GetString("Shortcut_ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel current operation.
        /// </summary>
        internal static string Shortcut_CancelCurrentOperation {
            get {
                return ResourceManager.GetString("Shortcut_CancelCurrentOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts for viewing details.
        /// </summary>
        internal static string Shortcut_Caption_DetailList {
            get {
                return ResourceManager.GetString("Shortcut_Caption_DetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard JAWS  shortcuts.
        /// </summary>
        internal static string Shortcut_Caption_JAWS {
            get {
                return ResourceManager.GetString("Shortcut_Caption_JAWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts used for editing the note filter.
        /// </summary>
        internal static string shortcut_Caption_NoteFilter {
            get {
                return ResourceManager.GetString("shortcut_Caption_NoteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts used for controlling the note list.
        /// </summary>
        internal static string shortcut_Caption_NoteList {
            get {
                return ResourceManager.GetString("shortcut_Caption_NoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts used for controlling the tempo.
        /// </summary>
        internal static string Shortcut_Caption_Tempo {
            get {
                return ResourceManager.GetString("Shortcut_Caption_Tempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Windows  shortcuts.
        /// </summary>
        internal static string Shortcut_Caption_Windows {
            get {
                return ResourceManager.GetString("Shortcut_Caption_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow the name of the chord.
        /// </summary>
        internal static string Shortcut_ChordName {
            get {
                return ResourceManager.GetString("Shortcut_ChordName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show top note in chord.
        /// </summary>
        internal static string Shortcut_ChordTop {
            get {
                return ResourceManager.GetString("Shortcut_ChordTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close program.
        /// </summary>
        internal static string Shortcut_CloseProgram {
            get {
                return ResourceManager.GetString("Shortcut_CloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease playback tempo.
        /// </summary>
        internal static string Shortcut_DecreaseTempo {
            get {
                return ResourceManager.GetString("Shortcut_DecreaseTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit details.
        /// </summary>
        internal static string Shortcut_EditDetails {
            get {
                return ResourceManager.GetString("Shortcut_EditDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Music Braille representation.
        /// </summary>
        internal static string Shortcut_EditMusicBraille {
            get {
                return ResourceManager.GetString("Shortcut_EditMusicBraille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit music playing parameters.
        /// </summary>
        internal static string Shortcut_EditMusicPlaying {
            get {
                return ResourceManager.GetString("Shortcut_EditMusicPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the note filter.
        /// </summary>
        internal static string Shortcut_EditNoteFilter {
            get {
                return ResourceManager.GetString("Shortcut_EditNoteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit textual representation.
        /// </summary>
        internal static string Shortcut_EditText {
            get {
                return ResourceManager.GetString("Shortcut_EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit voices.
        /// </summary>
        internal static string Shortcut_EditVoices {
            get {
                return ResourceManager.GetString("Shortcut_EditVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Shortcut_End {
            get {
                return ResourceManager.GetString("Shortcut_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand and edit the note filter.
        /// </summary>
        internal static string Shortcut_ExpandAndEditNoteFilter {
            get {
                return ResourceManager.GetString("Shortcut_ExpandAndEditNoteFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fised signature keys.
        /// </summary>
        internal static string Shortcut_FixedKeySignature {
            get {
                return ResourceManager.GetString("Shortcut_FixedKeySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to bottom line.
        /// </summary>
        internal static string Shortcut_GoToBottomLine {
            get {
                return ResourceManager.GetString("Shortcut_GoToBottomLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to measure n.
        /// </summary>
        internal static string Shortcut_GoToMeasureN {
            get {
                return ResourceManager.GetString("Shortcut_GoToMeasureN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to top line.
        /// </summary>
        internal static string Shortcut_GoToTopLine {
            get {
                return ResourceManager.GetString("Shortcut_GoToTopLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Shortcut_Home {
            get {
                return ResourceManager.GetString("Shortcut_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase playback tempo.
        /// </summary>
        internal static string Shortcut_IncreaseTempo {
            get {
                return ResourceManager.GetString("Shortcut_IncreaseTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show instruments.
        /// </summary>
        internal static string Shortcut_Instruments {
            get {
                return ResourceManager.GetString("Shortcut_Instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT.
        /// </summary>
        internal static string shortcut_Key_alt {
            get {
                return ResourceManager.GetString("shortcut_Key_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL.
        /// </summary>
        internal static string Shortcut_Key_Control {
            get {
                return ResourceManager.GetString("Shortcut_Key_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        internal static string Shortcut_Key_enter {
            get {
                return ResourceManager.GetString("Shortcut_Key_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC.
        /// </summary>
        internal static string Shortcut_Key_escape {
            get {
                return ResourceManager.GetString("Shortcut_Key_escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT.
        /// </summary>
        internal static string Shortcut_Key_insert {
            get {
                return ResourceManager.GetString("Shortcut_Key_insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGEDOWN.
        /// </summary>
        internal static string Shortcut_Key_pageDown {
            get {
                return ResourceManager.GetString("Shortcut_Key_pageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGEUP.
        /// </summary>
        internal static string Shortcut_Key_pageUp {
            get {
                return ResourceManager.GetString("Shortcut_Key_pageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT.
        /// </summary>
        internal static string shortcut_Key_shift {
            get {
                return ResourceManager.GetString("shortcut_Key_shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPACE.
        /// </summary>
        internal static string Shortcut_Key_space {
            get {
                return ResourceManager.GetString("Shortcut_Key_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB.
        /// </summary>
        internal static string shortcut_Key_tab {
            get {
                return ResourceManager.GetString("shortcut_Key_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help for keyboard shortcuts.
        /// </summary>
        internal static string Shortcut_MenuCaption {
            get {
                return ResourceManager.GetString("Shortcut_MenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show next detail.
        /// </summary>
        internal static string Shortcut_NextDetail {
            get {
                return ResourceManager.GetString("Shortcut_NextDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select next note.
        /// </summary>
        internal static string Shortcut_NextLine {
            get {
                return ResourceManager.GetString("Shortcut_NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select next measure.
        /// </summary>
        internal static string Shortcut_NextMeasure {
            get {
                return ResourceManager.GetString("Shortcut_NextMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select next part.
        /// </summary>
        internal static string Shortcut_NextPart {
            get {
                return ResourceManager.GetString("Shortcut_NextPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open FileOpen dialog.
        /// </summary>
        internal static string Shortcut_OpenFileOpenDialog {
            get {
                return ResourceManager.GetString("Shortcut_OpenFileOpenDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bottom part.
        /// </summary>
        internal static string Shortcut_PartBottom {
            get {
                return ResourceManager.GetString("Shortcut_PartBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show top part.
        /// </summary>
        internal static string Shortcut_PartTop {
            get {
                return ResourceManager.GetString("Shortcut_PartTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show previous detail.
        /// </summary>
        internal static string Shortcut_PreviousDetail {
            get {
                return ResourceManager.GetString("Shortcut_PreviousDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previous note.
        /// </summary>
        internal static string Shortcut_PreviousLine {
            get {
                return ResourceManager.GetString("Shortcut_PreviousLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previous measure.
        /// </summary>
        internal static string Shortcut_PreviousMeasure {
            get {
                return ResourceManager.GetString("Shortcut_PreviousMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previous part.
        /// </summary>
        internal static string Shortcut_PreviousPart {
            get {
                return ResourceManager.GetString("Shortcut_PreviousPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read message box.
        /// </summary>
        internal static string Shortcut_ReadMessagebox {
            get {
                return ResourceManager.GetString("Shortcut_ReadMessagebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the status line.
        /// </summary>
        internal static string Shortcut_ReadStatusLine {
            get {
                return ResourceManager.GetString("Shortcut_ReadStatusLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the title line.
        /// </summary>
        internal static string Shortcut_ReadTitleLine {
            get {
                return ResourceManager.GetString("Shortcut_ReadTitleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat from measure n to mesaure m.
        /// </summary>
        internal static string Shortcut_RepeatFromNtoM {
            get {
                return ResourceManager.GetString("Shortcut_RepeatFromNtoM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Menuline.
        /// </summary>
        internal static string Shortcut_SelectMenuLine {
            get {
                return ResourceManager.GetString("Shortcut_SelectMenuLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the note list.
        /// </summary>
        internal static string Shortcut_SelectNoteList {
            get {
                return ResourceManager.GetString("Shortcut_SelectNoteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the tempo for playing to n% of the tempo specified in the Musicxml file.
        /// </summary>
        internal static string Shortcut_SetTempo {
            get {
                return ResourceManager.GetString("Shortcut_SetTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing.
        /// </summary>
        internal static string Shortcut_StartPlaying {
            get {
                return ResourceManager.GetString("Shortcut_StartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing the current note.
        /// </summary>
        internal static string Shortcut_StopCurrentNote {
            get {
                return ResourceManager.GetString("Shortcut_StopCurrentNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playing.
        /// </summary>
        internal static string Shortcut_StopPlaying {
            get {
                return ResourceManager.GetString("Shortcut_StopPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string shortcut_Text_followedBy {
            get {
                return ResourceManager.GetString("shortcut_Text_followedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle between the note list and the note filter.
        /// </summary>
        internal static string Shortcut_ToggleBetweenListAndFilter {
            get {
                return ResourceManager.GetString("Shortcut_ToggleBetweenListAndFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle JAWS speech on / off.
        /// </summary>
        internal static string Shortcut_ToggleJAWSSpeechOnOff {
            get {
                return ResourceManager.GetString("Shortcut_ToggleJAWSSpeechOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle play on / off.
        /// </summary>
        internal static string Shortcut_TogglePlay {
            get {
                return ResourceManager.GetString("Shortcut_TogglePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle value on / off.
        /// </summary>
        internal static string Shortcut_ToggleValue {
            get {
                return ResourceManager.GetString("Shortcut_ToggleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected voice or detail off globally.
        /// </summary>
        internal static string Shortcut_TurnOffGlobally {
            get {
                return ResourceManager.GetString("Shortcut_TurnOffGlobally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn selected voice or detail on globally.
        /// </summary>
        internal static string Shurtcut_TurnOnGlobally {
            get {
                return ResourceManager.GetString("Shurtcut_TurnOnGlobally", resourceCulture);
            }
        }
    }
}
