//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrailleMusicDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForBrailleMusicDecoder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForBrailleMusicDecoder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrailleMusicDecoder.ResourcesForBrailleMusicDecoder", typeof(ResourcesForBrailleMusicDecoder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        internal static string AccidentalValueEnum_Flat {
            get {
                return ResourceManager.GetString("AccidentalValueEnum_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural.
        /// </summary>
        internal static string AccidentalValueEnum_Natural {
            get {
                return ResourceManager.GetString("AccidentalValueEnum_Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp.
        /// </summary>
        internal static string AccidentalValueEnum_Sharp {
            get {
                return ResourceManager.GetString("AccidentalValueEnum_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidental.
        /// </summary>
        internal static string InputCategoryEnum_Accidental {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Accidental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulation.
        /// </summary>
        internal static string InputCategoryEnum_Articulation {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Articulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        internal static string InputCategoryEnum_Beat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string InputCategoryEnum_Character {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clef.
        /// </summary>
        internal static string InputCategoryEnum_Clef {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Clef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        internal static string InputCategoryEnum_Denominator {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        internal static string InputCategoryEnum_Digit {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRepeat.
        /// </summary>
        internal static string InputCategoryEnum_EndRepeat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_EndRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger.
        /// </summary>
        internal static string InputCategoryEnum_Finger {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Finger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullEnd.
        /// </summary>
        internal static string InputCategoryEnum_FullEnd {
            get {
                return ResourceManager.GetString("InputCategoryEnum_FullEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HalfEnd.
        /// </summary>
        internal static string InputCategoryEnum_HalfEnd {
            get {
                return ResourceManager.GetString("InputCategoryEnum_HalfEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        internal static string InputCategoryEnum_Hand {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InAccordFullMeasure.
        /// </summary>
        internal static string InputCategoryEnum_InAccordFullMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InAccordFullMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InAccordPartMeasure.
        /// </summary>
        internal static string InputCategoryEnum_InAccordPartMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InAccordPartMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string InputCategoryEnum_Interval {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasureDivision.
        /// </summary>
        internal static string InputCategoryEnum_MeasureDivision {
            get {
                return ResourceManager.GetString("InputCategoryEnum_MeasureDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewMeasure.
        /// </summary>
        internal static string InputCategoryEnum_NewMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_NewMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string InputCategoryEnum_Note {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string InputCategoryEnum_Octave {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherValues.
        /// </summary>
        internal static string InputCategoryEnum_OtherValues {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OtherValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation.
        /// </summary>
        internal static string InputCategoryEnum_Punctuation {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string InputCategoryEnum_Rest {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur.
        /// </summary>
        internal static string InputCategoryEnum_Slur {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Slur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string InputCategoryEnum_Space {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextVersal.
        /// </summary>
        internal static string InputCategoryEnum_TextVersal {
            get {
                return ResourceManager.GetString("InputCategoryEnum_TextVersal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        internal static string InputCategoryEnum_Tie {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeModification.
        /// </summary>
        internal static string InputCategoryEnum_TimeModification {
            get {
                return ResourceManager.GetString("InputCategoryEnum_TimeModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToMusicBraille.
        /// </summary>
        internal static string InputCategoryEnum_ToMusicBraille {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToMusicBraille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToNumber.
        /// </summary>
        internal static string InputCategoryEnum_ToNumber {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToText.
        /// </summary>
        internal static string InputCategoryEnum_ToText {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToWord.
        /// </summary>
        internal static string InputCategoryEnum_ToWord {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnusualBarLine.
        /// </summary>
        internal static string InputCategoryEnum_UnusualBarLine {
            get {
                return ResourceManager.GetString("InputCategoryEnum_UnusualBarLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string InputCharacter_Uppercase {
            get {
                return ResourceManager.GetString("InputCharacter_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string InputValueArticulation_Accent {
            get {
                return ResourceManager.GetString("InputValueArticulation_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggio Down.
        /// </summary>
        internal static string InputValueArticulation_ArpeggioDown {
            get {
                return ResourceManager.GetString("InputValueArticulation_ArpeggioDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggio Up.
        /// </summary>
        internal static string InputValueArticulation_ArpeggioUp {
            get {
                return ResourceManager.GetString("InputValueArticulation_ArpeggioUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portamento.
        /// </summary>
        internal static string InputValueArticulation_Portamento {
            get {
                return ResourceManager.GetString("InputValueArticulation_Portamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portato.
        /// </summary>
        internal static string InputValueArticulation_Portato {
            get {
                return ResourceManager.GetString("InputValueArticulation_Portato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staccatissimo.
        /// </summary>
        internal static string InputValueArticulation_Staccatissimo {
            get {
                return ResourceManager.GetString("InputValueArticulation_Staccatissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staccato.
        /// </summary>
        internal static string InputValueArticulation_Staccato {
            get {
                return ResourceManager.GetString("InputValueArticulation_Staccato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenuto.
        /// </summary>
        internal static string InputValueArticulation_Tenuto {
            get {
                return ResourceManager.GetString("InputValueArticulation_Tenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string InputValueFullEnd_Reference {
            get {
                return ResourceManager.GetString("InputValueFullEnd_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string InputValueHand_Left {
            get {
                return ResourceManager.GetString("InputValueHand_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string InputValueHand_Right {
            get {
                return ResourceManager.GetString("InputValueHand_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermata.
        /// </summary>
        internal static string InputValueTimeModification_Fermata {
            get {
                return ResourceManager.GetString("InputValueTimeModification_Fermata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triplet.
        /// </summary>
        internal static string InputValueTimeModification_Triplet {
            get {
                return ResourceManager.GetString("InputValueTimeModification_Triplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string IntervalNameEnum_Fifth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string IntervalNameEnum_Fourth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string IntervalNameEnum_Octave {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string IntervalNameEnum_Second {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh.
        /// </summary>
        internal static string IntervalNameEnum_Seventh {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth.
        /// </summary>
        internal static string IntervalNameEnum_Sixth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string IntervalNameEnum_Third {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equality.
        /// </summary>
        internal static string OtherValuesNameEnum_Equality {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Equality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newline.
        /// </summary>
        internal static string OtherValuesNameEnum_NewLine {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornament.
        /// </summary>
        internal static string OtherValuesNameEnum_Ornament {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Ornament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trill.
        /// </summary>
        internal static string OtherValuesNameEnum_Trill {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Trill", resourceCulture);
            }
        }
    }
}
