//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrailleMusicDecoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesForBrailleMusicDecoder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesForBrailleMusicDecoder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrailleMusicDecoder.ResourcesForBrailleMusicDecoder", typeof(ResourcesForBrailleMusicDecoder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Decoder_AccumulatedText {
            get {
                return ResourceManager.GetString("Decoder_AccumulatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accidental.
        /// </summary>
        internal static string InputCategoryEnum_Accidental {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Accidental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articulation.
        /// </summary>
        internal static string InputCategoryEnum_Articulation {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Articulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat.
        /// </summary>
        internal static string InputCategoryEnum_Beat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Beat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string InputCategoryEnum_Character {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord extension.
        /// </summary>
        internal static string InputCategoryEnum_ChordNumericExtension {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordNumericExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chords.
        /// </summary>
        internal static string InputCategoryEnum_Chords {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Chords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord stem.
        /// </summary>
        internal static string InputCategoryEnum_ChordStemSign {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordStemSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord.
        /// </summary>
        internal static string InputCategoryEnum_ChordSymbol {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord bass note.
        /// </summary>
        internal static string InputCategoryEnum_ChordSymbolBass {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordSymbolBass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord.
        /// </summary>
        internal static string InputCategoryEnum_ChordSymbolRoot {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordSymbolRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord timing.
        /// </summary>
        internal static string InputCategoryEnum_ChordTiming {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ChordTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clef.
        /// </summary>
        internal static string InputCategoryEnum_Clef {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Clef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line.
        /// </summary>
        internal static string InputCategoryEnum_ControlCharCRLF {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ControlCharCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued line.
        /// </summary>
        internal static string InputCategoryEnum_ControlCharCRLFContinuedLine {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ControlCharCRLFContinuedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line, Measure number.
        /// </summary>
        internal static string InputCategoryEnum_ControlCharCRLFMeasureNumber {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ControlCharCRLFMeasureNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        internal static string InputCategoryEnum_ControlCharFF {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ControlCharFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        internal static string InputCategoryEnum_Denominator {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit.
        /// </summary>
        internal static string InputCategoryEnum_Digit {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special character.
        /// </summary>
        internal static string InputCategoryEnum_DigitSpecialCharacter {
            get {
                return ResourceManager.GetString("InputCategoryEnum_DigitSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics.
        /// </summary>
        internal static string InputCategoryEnum_EmbeddedTextDynamics {
            get {
                return ResourceManager.GetString("InputCategoryEnum_EmbeddedTextDynamics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string InputCategoryEnum_EmbeddedTextFreeText {
            get {
                return ResourceManager.GetString("InputCategoryEnum_EmbeddedTextFreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndRepeat.
        /// </summary>
        internal static string InputCategoryEnum_EndRepeat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_EndRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final double bar.
        /// </summary>
        internal static string InputCategoryEnum_FinalDoubleBar {
            get {
                return ResourceManager.GetString("InputCategoryEnum_FinalDoubleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger.
        /// </summary>
        internal static string InputCategoryEnum_Finger {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Finger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide dots.
        /// </summary>
        internal static string InputCategoryEnum_GuideDots {
            get {
                return ResourceManager.GetString("InputCategoryEnum_GuideDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        internal static string InputCategoryEnum_Hand {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyphen.
        /// </summary>
        internal static string InputCategoryEnum_Hyphen {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InAccordFullMeasure.
        /// </summary>
        internal static string InputCategoryEnum_InAccordFullMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InAccordFullMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InAccordPartMeasure.
        /// </summary>
        internal static string InputCategoryEnum_InAccordPartMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InAccordPartMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accord tie.
        /// </summary>
        internal static string InputCategoryEnum_InAccordTie {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InAccordTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted rest.
        /// </summary>
        internal static string InputCategoryEnum_InsertedRest {
            get {
                return ResourceManager.GetString("InputCategoryEnum_InsertedRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string InputCategoryEnum_Interval {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key signature.
        /// </summary>
        internal static string InputCategoryEnum_KeySignature {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key signature.
        /// </summary>
        internal static string InputCategoryEnum_KeySignatureText {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignatureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        internal static string InputCategoryEnum_KeySignatureTextFlat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignatureTextFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural.
        /// </summary>
        internal static string InputCategoryEnum_KeySignatureTextNatural {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignatureTextNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string InputCategoryEnum_KeySignatureTextNone {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignatureTextNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharp.
        /// </summary>
        internal static string InputCategoryEnum_KeySignatureTextSharp {
            get {
                return ResourceManager.GetString("InputCategoryEnum_KeySignatureTextSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continued line.
        /// </summary>
        internal static string InputCategoryEnum_LineContinuation {
            get {
                return ResourceManager.GetString("InputCategoryEnum_LineContinuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowered digit.
        /// </summary>
        internal static string InputCategoryEnum_LoweredDigit {
            get {
                return ResourceManager.GetString("InputCategoryEnum_LoweredDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MeasureDivision.
        /// </summary>
        internal static string InputCategoryEnum_MeasureDivision {
            get {
                return ResourceManager.GetString("InputCategoryEnum_MeasureDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewMeasure.
        /// </summary>
        internal static string InputCategoryEnum_NewMeasure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_NewMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string InputCategoryEnum_Note {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string InputCategoryEnum_Octave {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherValues.
        /// </summary>
        internal static string InputCategoryEnum_OtherValues {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OtherValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornament.
        /// </summary>
        internal static string InputCategoryEnum_Othervalues_Ornament {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Othervalues_Ornament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition start.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesDoubleBarFollowedByDots {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesDoubleBarFollowedByDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition end.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesDoubleBarPrecededByDots {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesDoubleBarPrecededByDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endings.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesIntervalEnding {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesIntervalEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long appoggiatura.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesLongAppoggiatura {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesLongAppoggiatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesNumericEnding {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesNumericEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partmeasure repeat.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesPartMeasureRepeat {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesPartMeasureRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First ending.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesPrimaVoltaFirstEnding {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesPrimaVoltaFirstEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second ending.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesPrimaVoltaSecondEnding {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesPrimaVoltaSecondEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short appoggiatura.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesShortAppoggiatura {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesShortAppoggiatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trill.
        /// </summary>
        internal static string InputCategoryEnum_OthervaluesTrill {
            get {
                return ResourceManager.GetString("InputCategoryEnum_OthervaluesTrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        internal static string InputCategoryEnum_PageNumber {
            get {
                return ResourceManager.GetString("InputCategoryEnum_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        internal static string InputCategoryEnum_PrintPagination {
            get {
                return ResourceManager.GetString("InputCategoryEnum_PrintPagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punctuation.
        /// </summary>
        internal static string InputCategoryEnum_Punctuation {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Punctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Braille fullmeasure repeat.
        /// </summary>
        internal static string InputCategoryEnum_RepeatSequence {
            get {
                return ResourceManager.GetString("InputCategoryEnum_RepeatSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measure.
        /// </summary>
        internal static string InputCategoryEnum_RepeatSequence_Measure {
            get {
                return ResourceManager.GetString("InputCategoryEnum_RepeatSequence_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to measures.
        /// </summary>
        internal static string InputCategoryEnum_RepeatSequence_Measures {
            get {
                return ResourceManager.GetString("InputCategoryEnum_RepeatSequence_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string InputCategoryEnum_Rest {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HalfEnd.
        /// </summary>
        internal static string InputCategoryEnum_SectionalDoubleBar {
            get {
                return ResourceManager.GetString("InputCategoryEnum_SectionalDoubleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string InputCategoryEnum_SectionHeader {
            get {
                return ResourceManager.GetString("InputCategoryEnum_SectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur.
        /// </summary>
        internal static string InputCategoryEnum_Slur {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Slur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small inverted arch above note.
        /// </summary>
        internal static string InputCategoryEnum_SmallInvertedArchAboveNote {
            get {
                return ResourceManager.GetString("InputCategoryEnum_SmallInvertedArchAboveNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string InputCategoryEnum_Space {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextVersal.
        /// </summary>
        internal static string InputCategoryEnum_TextVersal {
            get {
                return ResourceManager.GetString("InputCategoryEnum_TextVersal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textversals.
        /// </summary>
        internal static string InputCategoryEnum_TextVersals {
            get {
                return ResourceManager.GetString("InputCategoryEnum_TextVersals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie.
        /// </summary>
        internal static string InputCategoryEnum_Tie {
            get {
                return ResourceManager.GetString("InputCategoryEnum_Tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeModification.
        /// </summary>
        internal static string InputCategoryEnum_TimeModification {
            get {
                return ResourceManager.GetString("InputCategoryEnum_TimeModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToMusicBraille.
        /// </summary>
        internal static string InputCategoryEnum_ToMusicBraille {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToMusicBraille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToNumber.
        /// </summary>
        internal static string InputCategoryEnum_ToNumber {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To lowered digit.
        /// </summary>
        internal static string InputCategoryEnum_ToNumberLowered {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToNumberLowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToText.
        /// </summary>
        internal static string InputCategoryEnum_ToText {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToWord.
        /// </summary>
        internal static string InputCategoryEnum_ToWord {
            get {
                return ResourceManager.GetString("InputCategoryEnum_ToWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnusualBarLine.
        /// </summary>
        internal static string InputCategoryEnum_UnusualBarLine {
            get {
                return ResourceManager.GetString("InputCategoryEnum_UnusualBarLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string InputCharacter_Uppercase {
            get {
                return ResourceManager.GetString("InputCharacter_Uppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courtesy flat.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalCourtesyFlat {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalCourtesyFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courtesy natural.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalCourtesyNatural {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalCourtesyNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courtesy sharp.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalCourtesySharp {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalCourtesySharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalFlat {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalNatural {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp.
        /// </summary>
        internal static string InputSubCategoryEnum_AccidentalSharp {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_AccidentalSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty space.
        /// </summary>
        internal static string InputSubCategoryEnum_Blank {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty spaces.
        /// </summary>
        internal static string InputSubCategoryEnum_BlankSequence {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_BlankSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to augmented.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordAugmented {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordAugmented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dim.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordDiminished {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to half diminished.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordHalfDiminished {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordHalfDiminished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maj 7.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordMaj7 {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordMaj7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordMinor {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordMinor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus 4.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSus2 {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sus 4.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSus4 {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSymbolFlat {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSymbolFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to natural.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSymbolNatural {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSymbolNatural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord no root.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSymbolRootNoRoot {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSymbolRootNoRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharp.
        /// </summary>
        internal static string InputSubCategoryEnum_ChordSymbolSharp {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_ChordSymbolSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraction.
        /// </summary>
        internal static string InputSubCategoryEnum_Contraction {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_Contraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crescendo end.
        /// </summary>
        internal static string InputSubCategoryEnum_CrescendoEnd {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_CrescendoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crescendo start.
        /// </summary>
        internal static string InputSubCategoryEnum_CrescendoStart {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_CrescendoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuendo end.
        /// </summary>
        internal static string InputSubCategoryEnum_DiminuendoEnd {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_DiminuendoEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diminuendo start.
        /// </summary>
        internal static string InputSubCategoryEnum_DiminuendoStart {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_DiminuendoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphic symbol Segno.
        /// </summary>
        internal static string InputSubCategoryEnum_GraphicSymbolSegno {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_GraphicSymbolSegno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left hand.
        /// </summary>
        internal static string InputSubCategoryEnum_LeftHand {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_LeftHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full measure repeat.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesFullMeasureRepeat {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesFullMeasureRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full measure repeat without initial empty space.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesFullMeasureRepeatNoInitialBlank {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesFullMeasureRepeatNoInitialBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full measure repeat once.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesFullMeasureRepeatOnce {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesFullMeasureRepeatOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full measure repeat twice.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesFullMeasureRepeatTwice {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesFullMeasureRepeatTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part measure repeat twice.
        /// </summary>
        internal static string InputSubCategoryEnum_OtherValuesPartMeasureRepeatTwice {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OtherValuesPartMeasureRepeatTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternating notes repeated with tremolo.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesTremoloAlternatingNotes {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesTremoloAlternatingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note repeated with tremolo.
        /// </summary>
        internal static string InputSubCategoryEnum_OthervaluesTremoloRepeatedNote {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_OthervaluesTremoloRepeatedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piano pedal down.
        /// </summary>
        internal static string InputSubCategoryEnum_PianoPedalDown {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_PianoPedalDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right hand.
        /// </summary>
        internal static string InputSubCategoryEnum_RightHand {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_RightHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur.
        /// </summary>
        internal static string InputSubCategoryEnum_SlurDefault {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlurDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double slur.
        /// </summary>
        internal static string InputSubCategoryEnum_SlurDouble {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlurDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur stop.
        /// </summary>
        internal static string InputSubCategoryEnum_SlurEndBracketSlur {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlurEndBracketSlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur.
        /// </summary>
        internal static string InputSubCategoryEnum_SlurNormal {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlurNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur start.
        /// </summary>
        internal static string InputSubCategoryEnum_SlurStartBracketSlur {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlurStartBracketSlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slur without endpoint.
        /// </summary>
        internal static string InputSubCategoryEnum_SlursThatDoNotLeadtoNotes {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SlursThatDoNotLeadtoNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square bracket below staff end.
        /// </summary>
        internal static string InputSubCategoryEnum_SquareBracketBelowStaffEnd {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SquareBracketBelowStaffEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square bracket below staff start.
        /// </summary>
        internal static string InputSubCategoryEnum_SquareBracketBelowStaffStart {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_SquareBracketBelowStaffStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline end.
        /// </summary>
        internal static string InputSubCategoryEnum_TypeFormIndicatorUnderlineEnd {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_TypeFormIndicatorUnderlineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline start.
        /// </summary>
        internal static string InputSubCategoryEnum_TypeFormIndicatorUnderlineStart {
            get {
                return ResourceManager.GetString("InputSubCategoryEnum_TypeFormIndicatorUnderlineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent.
        /// </summary>
        internal static string InputValueArticulation_Accent {
            get {
                return ResourceManager.GetString("InputValueArticulation_Accent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggio Down.
        /// </summary>
        internal static string InputValueArticulation_ArpeggioDown {
            get {
                return ResourceManager.GetString("InputValueArticulation_ArpeggioDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arpeggio Up.
        /// </summary>
        internal static string InputValueArticulation_ArpeggioUp {
            get {
                return ResourceManager.GetString("InputValueArticulation_ArpeggioUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portamento.
        /// </summary>
        internal static string InputValueArticulation_Portamento {
            get {
                return ResourceManager.GetString("InputValueArticulation_Portamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portato.
        /// </summary>
        internal static string InputValueArticulation_Portato {
            get {
                return ResourceManager.GetString("InputValueArticulation_Portato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staccatissimo.
        /// </summary>
        internal static string InputValueArticulation_Staccatissimo {
            get {
                return ResourceManager.GetString("InputValueArticulation_Staccatissimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staccato.
        /// </summary>
        internal static string InputValueArticulation_Staccato {
            get {
                return ResourceManager.GetString("InputValueArticulation_Staccato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenuto.
        /// </summary>
        internal static string InputValueArticulation_Tenuto {
            get {
                return ResourceManager.GetString("InputValueArticulation_Tenuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string InputValueFullEnd_Reference {
            get {
                return ResourceManager.GetString("InputValueFullEnd_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left hand.
        /// </summary>
        internal static string InputValueHand_Left {
            get {
                return ResourceManager.GetString("InputValueHand_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right hand.
        /// </summary>
        internal static string InputValueHand_Right {
            get {
                return ResourceManager.GetString("InputValueHand_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermata.
        /// </summary>
        internal static string InputValueTimeModification_Fermata {
            get {
                return ResourceManager.GetString("InputValueTimeModification_Fermata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triplet.
        /// </summary>
        internal static string InputValueTimeModification_Triplet {
            get {
                return ResourceManager.GetString("InputValueTimeModification_Triplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        internal static string IntervalNameEnum_Fifth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        internal static string IntervalNameEnum_Fourth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string IntervalNameEnum_Octave {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Octave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        internal static string IntervalNameEnum_Second {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh.
        /// </summary>
        internal static string IntervalNameEnum_Seventh {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth.
        /// </summary>
        internal static string IntervalNameEnum_Sixth {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        internal static string IntervalNameEnum_Third {
            get {
                return ResourceManager.GetString("IntervalNameEnum_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flat.
        /// </summary>
        internal static string Note_A_Flat {
            get {
                return ResourceManager.GetString("Note_A_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sharp.
        /// </summary>
        internal static string Note_A_Sharp {
            get {
                return ResourceManager.GetString("Note_A_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B flat.
        /// </summary>
        internal static string Note_B_Flat {
            get {
                return ResourceManager.GetString("Note_B_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B sharp.
        /// </summary>
        internal static string Note_B_Sharp {
            get {
                return ResourceManager.GetString("Note_B_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C flat.
        /// </summary>
        internal static string Note_C_Flat {
            get {
                return ResourceManager.GetString("Note_C_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C sharp.
        /// </summary>
        internal static string Note_C_Sharp {
            get {
                return ResourceManager.GetString("Note_C_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D flat.
        /// </summary>
        internal static string Note_D_Flat {
            get {
                return ResourceManager.GetString("Note_D_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D sharp.
        /// </summary>
        internal static string Note_D_Sharp {
            get {
                return ResourceManager.GetString("Note_D_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E flat.
        /// </summary>
        internal static string Note_E_Flat {
            get {
                return ResourceManager.GetString("Note_E_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E sharp.
        /// </summary>
        internal static string Note_E_Sharp {
            get {
                return ResourceManager.GetString("Note_E_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F flat.
        /// </summary>
        internal static string Note_F_Flat {
            get {
                return ResourceManager.GetString("Note_F_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F_Sharp.
        /// </summary>
        internal static string Note_F_Sharp {
            get {
                return ResourceManager.GetString("Note_F_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G flat.
        /// </summary>
        internal static string Note_G_Flat {
            get {
                return ResourceManager.GetString("Note_G_Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G_Sharp.
        /// </summary>
        internal static string Note_G_Sharp {
            get {
                return ResourceManager.GetString("Note_G_Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equality.
        /// </summary>
        internal static string OtherValuesNameEnum_Equality {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Equality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewLine.
        /// </summary>
        internal static string OtherValuesNameEnum_NewLine {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_NewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ornament.
        /// </summary>
        internal static string OtherValuesNameEnum_Ornament {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Ornament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trill.
        /// </summary>
        internal static string OtherValuesNameEnum_Trill {
            get {
                return ResourceManager.GetString("OtherValuesNameEnum_Trill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOT.
        /// </summary>
        internal static string Text_Dot {
            get {
                return ResourceManager.GetString("Text_Dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Text_Line {
            get {
                return ResourceManager.GetString("Text_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No interpretation for.
        /// </summary>
        internal static string Text_noInterpretationFor {
            get {
                return ResourceManager.GetString("Text_noInterpretationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Text_Page {
            get {
                return ResourceManager.GetString("Text_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        internal static string Text_Space {
            get {
                return ResourceManager.GetString("Text_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Text_Warning {
            get {
                return ResourceManager.GetString("Text_Warning", resourceCulture);
            }
        }
    }
}
