using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Reflection;

//*****************************************************************************************************************
// NOTE: Please see the ReadMe.txt file in this project for relevant information about the usage of this project! *
//*****************************************************************************************************************

namespace LocalizationAnalyzer
{
    [Flags]
    public enum Options { UseConsole = 1, WaitForKey = 2 }
    public enum CultureEnum { unchanged, daDK, enUS, enGB, nlNL, ruRU }
    public enum RessourcesEnum { BrailleMusicDecoder, MusicSynthesis, MusicXmlReaderModel, MusicXmlReaderUI, MusicXmlReaderHelp, MusicXmlReaderSettings }

    public class Analyzer
    {
        public const Options noOptions = 0;
        private System.Threading.Thread thisThread;
        private string dllDirectory;
        private List<RessourcesEnum> resources;
        private const string BrailleMusicDecoderName = "BrailleMusicDecoder.dll";
        private const string MusicSynthesisName = "MusicSynthesis.dll";
        private const string MusicXmlReaderModelName = "MusicXmlReaderModel.dll";
        private const string MusicXmlReaderName = "Tactile MusicXmlReader.exe";
        private Counters counters;
        private List<TranslationList> translationLists; // For jolding all results
        private List<CultureEnum> cultures;
        public List<CultureEnum> Cultures { get { return cultures; } }
        private string basePath; // Base directory for all files generated, including the logfile
        public string BasePath { get { return basePath; } } // Base directory for all files generated, including the logfile
        private static bool useConsole;
        private static bool waitForKey;
        // Bindingflags is used for filtering methods. All autogenerated localization methods are static and non-public.
        private const BindingFlags bindingFlags = (BindingFlags.NonPublic | BindingFlags.Static);
        private readonly string bindingFlagsString = bindingFlags.ToString();
        private Translation.LogOptions translationLogOptions = Translation.LogOptions.LogKeyValuePairs | Translation.LogOptions.LogIgnoredMethods;
        //        private Translation.LogOptions translationLogOptions = Translation.LogOptions.LogIgnoredMethods;
        // private Translation.LogOptions translationLogOptions = 0;

        public static Analyzer Create(string basePath)
        {
            return new Analyzer(basePath, 0);
        }

        public static Analyzer Create(string basePath, Options options)
        {
            return new Analyzer(basePath, options);
        }

        private Analyzer(string basePath, Options options)
        {
            Options maskedValue;
            maskedValue = (options & Options.UseConsole);
            useConsole = (maskedValue == Options.UseConsole);
            // Only wait for key when UseConsole and WaitForKey are BOTH set!
            maskedValue = (options & (Options.UseConsole | Options.WaitForKey));
            waitForKey = (maskedValue == (Options.UseConsole | Options.WaitForKey));
            this.basePath = basePath;
            if (!Directory.Exists(this.basePath))
            {
                Directory.CreateDirectory(this.basePath);
            }
        }

        private Analyzer() { }

        public void Execute()
        {
            Console.BufferHeight = 10000; // Make room for 10000 lines
            LocalizationLogger.Init();
            thisThread = System.Threading.Thread.CurrentThread;
            System.Globalization.CultureInfo originalCultureInfo = thisThread.CurrentUICulture; // Save the original CultureInfo
            try // Be sure to have a global logfile whatever happens !
            {

#warning todo accept the path as a parameter to the .exe file

                dllDirectory = GetDllDirectory();               // The path to the dlls to analyze  

                if (waitForKey)
                {
                    Console.WriteLine("Press any key to continue");
                    Console.ReadKey();
                }

                cultures = new List<CultureEnum>    // The  cultures to analyze
            {
                //CultureEnum.unchanged,         // Use default culture
                CultureEnum.daDK,
                CultureEnum.enUS,
                //CultureEnum.enGB,
                CultureEnum.nlNL,
                CultureEnum.ruRU,
            };



                resources = new List<RessourcesEnum> // resources to analyze
            {
                RessourcesEnum.BrailleMusicDecoder,
                RessourcesEnum.MusicSynthesis,
                RessourcesEnum.MusicXmlReaderModel,
                RessourcesEnum.MusicXmlReaderUI,
                RessourcesEnum.MusicXmlReaderSettings,
                RessourcesEnum.MusicXmlReaderHelp,
            };



                translationLists = new List<TranslationList>();

       

                foreach (CultureEnum culture in cultures)
                {
                    GetTranslations(culture);
                }

                foreach (TranslationList translationList in translationLists)
                {
                    Log(translationList.ToString());
                }


                foreach (RessourcesEnum resource in resources)
                {
                    Log(string.Format("Resource='{0}'-----------------------------------------------------", resource.ToString()));
                    TranslationMatrix tm = TranslationMatrix.Create(translationLists, resource);
                    List<string> strings = tm.ToStrings();
                    LocalizationLogger.Log(strings);
                    //WriteToFile(@"C:\temp\DeveloperTool." + resource.ToString() + ".txt", strings);
                    WriteToFile(Path.Combine(basePath,"DeveloperTool." + resource.ToString() + ".txt"), strings);
                }
            }
            catch (Exception e)
            {
                Log(string.Format("Exception.Message='{0}'", e.Message));
            }

            thisThread.CurrentUICulture = originalCultureInfo; // Finally restore the original CultureInfo

            Log(string.Format("Saving results at '{0}'", basePath));

            // Write the whole LocalizationLog to file
            LocalizationLogger.WriteToFile(Path.Combine(basePath,"GlobalLog.txt"));
            //WriteToFile(@"C:\temp\DeveloperTool.GlobalLog.txt", GlobalLog);
            if (waitForKey)
            {
                Log("Press any key to exit");
                Console.ReadKey();
            }
        }

        static string GetDllDirectory()
        {
            // If no parameter was found we assume we are in a development scenario
            string currentDirectory = System.Environment.CurrentDirectory;
            Log(string.Format("CurrentDirectory={0}", currentDirectory));
            string visualStudioDirectory = currentDirectory.Remove(currentDirectory.LastIndexOf("Solution"));
            string result  = Path.Combine(visualStudioDirectory, @"Solutions\Tactile MusicXmlReader\MusicXmlReader\bin\Debug");
            Log(string.Format("DllDirectory={0}", result));
            bool found = Directory.Exists(result);
            Log(string.Format("{0} '{1}'", found ? "Found " : "Directory not found: ",result));
            if (!found) Exit();
            return result;
        }



        static void Exit()
        {
            //Log("\r\nPress any key to exit");
            //Console.ReadLine();
            Log("\r\n");
            System.Environment.Exit(0);            
        }

        private void GetTranslations(CultureEnum culture)
        {
            string cultureName = ToString(culture);
            if (!string.IsNullOrEmpty(cultureName))
            {
                ChangeCulture(cultureName);
            };

            //Log(string.Format("Culture='{0}'", thisThread.CurrentCulture.ToString()));

            foreach (RessourcesEnum resource in resources)
            {
               
                TypeId typeId = ToTypeId(resource);
                List<Translation> translations = GetTranslationsForAssembly(typeId);
                TranslationList translationList = TranslationList.Create(culture, resource, translations);
                translationLists.Add(translationList);
            }
        }



        private List<Translation> GetTranslationsForAssembly(TypeId typeId)
        {

            // https://stackoverflow.com/questions/43802790/access-internal-method-in-a-sealed-class-c-sharp

            //using System.Reflection;
            //Type t = typeof(YourSealedClass); //get the type of your class
            //YourSealedClass obj = new YourSealedClass(); //somehow get the instance of the class
            ////find all non public methods
            //MethodInfo[] methods = t.GetMethods(BindingFlags.NonPublic | BindingFlags.Instance);
            ////next find your method. You can use LINQ or good old loop:
            //foreach (MethodInfo mi in methods)
            //    if (mi.Name == "MethodYouWantToUse")
            //    {
            //        mi.Invoke(obj, null);
            //        break; //leave the loop
            //    }
            List<Translation> result = new List<Translation>();

            string assemblyFullPath = Path.Combine(dllDirectory, typeId.AssemblyName);
            bool found = File.Exists(assemblyFullPath);
            Log(string.Format("{0} '{1}'", found ? "\r\nFound " : "FileNot found: ", assemblyFullPath));
            Assembly assembly = System.Reflection.Assembly.LoadFile(assemblyFullPath);
            Log(string.Format("Loaded assembly {0}", assembly.FullName));

            Experiment.Execute(assembly, typeId);

            // IEnumerable<TypeInfo> definedTypeInfos = assembly.DefinedTypes;
#if false
            Type[] types = null;
            try
            {
                types = assembly.GetTypes();
            }
            catch (ReflectionTypeLoadException e)
            {
                // If one ore more types can not be loaded an exception is thrown and the actually loeded types can br found in its Types property:
                int failures = 0;
                int successes = 0;
                Log(string.Format("Exception thrown by GetTypes() for Assembly='{0}'", assembly.FullName));
                Log(string.Format("Exception.Message={0}", e.Message));
                Console.WriteLine("Press any key to continue");
                Console.ReadKey();
                Exception[] exceptions = e.LoaderExceptions;
                foreach (Exception ex in exceptions)
                {
                    Log(string.Format("Message={0}", ex.Message));
                }
                foreach (Type type in e.Types)
                {
                    if (null == type)
                        failures++;
                    else
                        successes++;
                    //Log(string.Format("********************************************Type.Name={0}",(null == type) ? "Null" : type.Name));
                }
                Log(string.Format("********************************************Loaded {0} types. Failed to load {1} types", successes, failures));
                types = e.Types;
                Console.WriteLine("Press any key to continue");
                Console.ReadKey();
            }

            Type resource = null;
            foreach (Type type in types)
            {
                if (null != type)
                {
                    if (type.Name.Equals(typeId.TypeName))
                    {
                        resource = type;
                        break; // Out of foreach
                    }
                }
            }
#else
#warning todo: Consider using assembly.GetType() instead of assembly.GetTypes(). This requires knowledge of the NameSpace for the resource!
            string s = string.Format("{0}.{1}", typeId.NameSpaceName, typeId.TypeName);
            Type resource = assembly.GetType(s);
#endif

            if (null != resource)
            {        
                MemberInfo[] members = resource.GetMembers(bindingFlags);
                Log(string.Format("Assembly='{0}' TypeName='{1}' contains {2} methods with BindingFlags=({3})", typeId.AssemblyName, typeId.TypeName, members.Length, bindingFlagsString));
                counters = Counters.Create();

                foreach (MemberInfo memberInfo in members)
                {
                    Translation translation = Translation.Create(memberInfo,counters, translationLogOptions); // As we only call static methods the myClass paramtere is null
                    if (null != translation)
                    {
                        result.Add(translation);
                    }
                }
                Log(counters.LogFormat());
            }
            return result;
        }
        
        void ChangeCulture(string newCultureName)
        {
            Log(string.Format("\r\n******Culture changed to '{0}'******\r\n", newCultureName));
            thisThread.CurrentUICulture = new System.Globalization.CultureInfo(newCultureName);
        }

        // Just a simple shorthand.
        public static void Log(string s)
        {
            LocalizationLogger.Log(s);
        }
        
        static void WriteToFile(string fileName, List<string> strings)
        {
            System.IO.File.WriteAllLines(fileName, strings);   
        }

        static public string ToString(CultureEnum cultureEnum)
        {
            switch (cultureEnum)
            {
                case CultureEnum.unchanged: return "";
                case CultureEnum.daDK: return "da-DK";
                case CultureEnum.enUS: return "en-US";
                case CultureEnum.enGB: return "en-GB";
                case CultureEnum.nlNL: return "nl-NL";
                case CultureEnum.ruRU: return "ru-RU";
            }
            return null; // To force an error
        }

        static public TypeId ToTypeId(RessourcesEnum ressourcesEnum)
        {
            switch (ressourcesEnum)
            {
                case RessourcesEnum.BrailleMusicDecoder: return TypeId.Create(BrailleMusicDecoderName, "ResourcesForBrailleMusicDecoder", "BrailleMusicDecoder");
                case RessourcesEnum.MusicSynthesis: return TypeId.Create(MusicSynthesisName, "ResourcesForMusicSynthesis", "MusicSynthesis");
                case RessourcesEnum.MusicXmlReaderModel: return TypeId.Create(MusicXmlReaderModelName, "ResourcesForModel", "MusicXmlReaderModel");
                case RessourcesEnum.MusicXmlReaderUI: return TypeId.Create(MusicXmlReaderName, "ResourcesForUI", "MusicXmlReader");
                case RessourcesEnum.MusicXmlReaderSettings: return TypeId.Create(MusicXmlReaderName, "ResourcesForSettings", "MusicXmlReader");
                case RessourcesEnum.MusicXmlReaderHelp: return TypeId.Create(MusicXmlReaderName, "ResourcesForHelp", "MusicXmlReader");
            }
            return null; // To catch errors

        }


    }
}
