// Generated by .NET Reflector from C:\Users\Jens\Dropbox\Root\Visual Studio 2015\Projects\MusicXmlReaderUI\MusicSynthesis\bin\Debug\NAudio.dll
namespace NAudio.Midi
{
    using NAudio;
    using System;
    using System.Runtime.InteropServices;
    
    [StructLayout(LayoutKind.Sequential, CharSet=CharSet.Auto)]
    public struct MidiOutCapabilities
    {
        private const int MaxProductNameLength = 0x20;
        private short manufacturerId;
        private short productId;
        private int driverVersion;
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst=0x20)]
        private string productName;
        private short wTechnology;
        private short wVoices;
        private short wNotes;
        private ushort wChannelMask;
        private MidiOutCapabilityFlags dwSupport;
        public Manufacturers Manufacturer
        {
            get
            {
                return (Manufacturers) this.manufacturerId;
            }
        }
        public short ProductId
        {
            get
            {
                return this.productId;
            }
        }
        public string ProductName
        {
            get
            {
                return this.productName;
            }
        }
        public int Voices
        {
            get
            {
                return this.wVoices;
            }
        }
        public int Notes
        {
            get
            {
                return this.wNotes;
            }
        }
        public bool SupportsAllChannels
        {
            get
            {
                return (this.wChannelMask == 0xffff);
            }
        }
        public bool SupportsChannel(int channel)
        {
            return ((this.wChannelMask & (((int) 1) << (channel - 1))) > 0);
        }
        
        public bool SupportsPatchCaching
        {
            get
            {
                return ((this.dwSupport & MidiOutCapabilityFlags.PatchCaching) != 0);
            }
        }
        public bool SupportsSeparateLeftAndRightVolume
        {
            get
            {
                return ((this.dwSupport & MidiOutCapabilityFlags.LeftRightVolume) != 0);
            }
        }
        public bool SupportsMidiStreamOut
        {
            get
            {
                return ((this.dwSupport & MidiOutCapabilityFlags.Stream) != 0);
            }
        }
        public bool SupportsVolumeControl
        {
            get
            {
                return ((this.dwSupport & MidiOutCapabilityFlags.Volume) != 0);
            }
        }
        public MidiOutTechnology Technology
        {
            get
            {
                return (MidiOutTechnology) this.wTechnology;
            }
        }
        [Flags]
        private enum MidiOutCapabilityFlags
        {
            LeftRightVolume = 2,
            PatchCaching = 4,
            Stream = 8,
            Volume = 1
        }
    }
}
