// Generated by .NET Reflector from C:\Users\Jens\Dropbox\Root\Visual Studio 2015\Projects\MusicXmlReaderUI\MusicSynthesis\bin\Debug\NAudio.dll
namespace NAudio.Midi
{
    using NAudio;
    using System;
    using System.Runtime.InteropServices;
    
    public class MidiOut : IDisposable
    {
        private MidiInterop.MidiOutCallback callback;
        private bool disposed;
        private IntPtr hMidiOut = IntPtr.Zero;
        
        public MidiOut(int deviceNo)
        {
            this.callback = new MidiInterop.MidiOutCallback(this.Callback);
            MmException.Try(MidiInterop.midiOutOpen(out this.hMidiOut, (IntPtr) deviceNo, this.callback, IntPtr.Zero, 0x30000), "midiOutOpen");
        }
        
        private void Callback(IntPtr midiInHandle, MidiInterop.MidiOutMessage message, IntPtr userData, IntPtr messageParameter1, IntPtr messageParameter2)
        {
        }
        
        public void Close()
        {
            this.Dispose();
        }
        
        public static MidiOutCapabilities DeviceInfo(int midiOutDeviceNumber)
        {
            MidiOutCapabilities structure = new MidiOutCapabilities();
            int uSize = Marshal.SizeOf(structure);
            MmException.Try(MidiInterop.midiOutGetDevCaps((IntPtr) midiOutDeviceNumber, out structure, uSize), "midiOutGetDevCaps");
            return structure;
        }
        
        public void Dispose()
        {
            GC.KeepAlive(this.callback);
            this.Dispose(true);
            GC.SuppressFinalize(this);
        }
        
        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                MidiInterop.midiOutClose(this.hMidiOut);
            }
            this.disposed = true;
        }
        
        ~MidiOut()
        {
            this.Dispose(false);
        }
        
        public void Reset()
        {
            MmException.Try(MidiInterop.midiOutReset(this.hMidiOut), "midiOutReset");
        }
        
        public void Send(int message)
        {
            MmException.Try(MidiInterop.midiOutShortMsg(this.hMidiOut, message), "midiOutShortMsg");
        }
        
        public void SendBuffer(byte[] byteBuffer)
        {
            MidiInterop.MIDIHDR structure = new MidiInterop.MIDIHDR {
                lpData = Marshal.AllocHGlobal(byteBuffer.Length)
            };
            Marshal.Copy(byteBuffer, 0, structure.lpData, byteBuffer.Length);
            structure.dwBufferLength = byteBuffer.Length;
            structure.dwBytesRecorded = byteBuffer.Length;
            int uSize = Marshal.SizeOf(structure);
            MidiInterop.midiOutPrepareHeader(this.hMidiOut, ref structure, uSize);
            if (MidiInterop.midiOutLongMsg(this.hMidiOut, ref structure, uSize) != MmResult.NoError)
            {
                MidiInterop.midiOutUnprepareHeader(this.hMidiOut, ref structure, uSize);
            }
            Marshal.FreeHGlobal(structure.lpData);
        }
        
        public void SendDriverMessage(int message, int param1, int param2)
        {
            MmException.Try(MidiInterop.midiOutMessage(this.hMidiOut, message, (IntPtr) param1, (IntPtr) param2), "midiOutMessage");
        }
        
        public static int NumberOfDevices
        {
            get
            {
                return MidiInterop.midiOutGetNumDevs();
            }
        }
        
        public int Volume
        {
            get
            {
                int lpdwVolume = 0;
                MmException.Try(MidiInterop.midiOutGetVolume(this.hMidiOut, ref lpdwVolume), "midiOutGetVolume");
                return lpdwVolume;
            }
            set
            {
                MmException.Try(MidiInterop.midiOutSetVolume(this.hMidiOut, value), "midiOutSetVolume");
            }
        }
    }
}
